#ifndef RISCV_OPC_SFPU_INSNS_H
#define RISCV_OPC_SFPU_INSNS_H

// FIXME: Naming should be tt.$name
{"sfpload",    0, INSN_CLASS_XTTGS,   "Jd1,Jn,Jm1",     MATCH_SFPLOAD,   MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfpload",    0, INSN_CLASS_XTTWH,   "Jd1,Jq,Jm1,Jp",  MATCH_SFPLOAD,   MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfpload",    0, INSN_CLASS_XTTBH,   "Jd1,Jxa3,Jm1,Jxa2",MATCH_SFPLOAD, MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_XTTGS,   "Jd1,Jn,Jm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_XTTWH,   "Jd1,Jn,Jm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_XTTBH,   "Jd1,Jn,Jm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },	
{"sfpstore",   0, INSN_CLASS_XTTGS,   "Jn,Jd2,Jm2",     MATCH_SFPSTORE,  MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },
{"sfpstore",   0, INSN_CLASS_XTTWH,   "Jq,Jd2,Jm1,Jp",  MATCH_SFPSTORE,  MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },
{"sfpstore",   0, INSN_CLASS_XTTBH,   "Jxa3,Jd2,Jm1,Jxa2",MATCH_SFPSTORE,MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },	
{"sfplut",     0, INSN_CLASS_XTTGS,   "Jd1,Jm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },
{"sfplut",     0, INSN_CLASS_XTTWH,   "Jd1,Jm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },
{"sfplut",     0, INSN_CLASS_XTTBH,   "Jd1,Jm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },	
{"sfpmuli",    0, INSN_CLASS_XTTGS,   "Jh,Jj,Ji3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },
{"sfpmuli",    0, INSN_CLASS_XTTWH,   "Jh,Jj,Ji3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },
{"sfpmuli",    0, INSN_CLASS_XTTBH,   "Jh,Jj,Ji3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },	
{"sfpaddi",    0, INSN_CLASS_XTTGS,   "Jh,Jj,Ji3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },
{"sfpaddi",    0, INSN_CLASS_XTTWH,   "Jh,Jj,Ji3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },
{"sfpaddi",    0, INSN_CLASS_XTTBH,   "Jh,Jj,Ji3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },	
{"sfpdivp2",   0, INSN_CLASS_XTTGS,   "Jh,Jg,Jf,Ji2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },
{"sfpdivp2",   0, INSN_CLASS_XTTWH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },
{"sfpdivp2",   0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },	
{"sfpexexp",   0, INSN_CLASS_XTTGS,   "Jh,Jg,Ji4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },
{"sfpexexp",   0, INSN_CLASS_XTTWH,   "Jh,Jg,Ji4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },
{"sfpexexp",   0, INSN_CLASS_XTTBH,   "Jh,Jg,Ji4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },	
{"sfpexman",   0, INSN_CLASS_XTTGS,   "Jh,Jg,Ji2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },
{"sfpexman",   0, INSN_CLASS_XTTWH,   "Jh,Jg,Ji2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },
{"sfpexman",   0, INSN_CLASS_XTTBH,   "Jh,Jg,Ji2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },	
{"sfpiadd",    0, INSN_CLASS_XTTGS,   "Jh,Jg,Jf,Ji5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },
{"sfpiadd",    0, INSN_CLASS_XTTWH,   "Jh,Jg,Jf,Ji5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },
{"sfpiadd",    0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },	
{"sfpshft",    0, INSN_CLASS_XTTGS,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },
{"sfpshft",    0, INSN_CLASS_XTTWH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },
{"sfpshft",    0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },	
{"sfpabs",     0, INSN_CLASS_XTTGS,   "Jh,Jg,Ji2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpabs",     0, INSN_CLASS_XTTWH,   "Jh,Jg,Ji2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpabs",     0, INSN_CLASS_XTTBH,   "Jh,Jg,Ji2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_XTTGS,   "Jh,Jg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_XTTWH,   "Jh,Jg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_XTTBH,   "Jh,Jg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_XTTGS,   "Jh,Jg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_XTTWH,   "Jh,Jg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_XTTBH,   "Jh,Jg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_XTTGS,   "Jh,Jg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_XTTWH,   "Jh,Jg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_XTTBH,   "Jh,Jg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_XTTGS,   "Jh,Jg,Ji6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_XTTWH,   "Jh,Jg,Ji6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_XTTBH,   "Jh,Jg,Ji6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_XTTGS,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_XTTWH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_XTTGS,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_XTTWH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_XTTGS,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_XTTWH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_XTTGS,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_XTTWH,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_XTTBH,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_XTTGS,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_XTTWH,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_XTTBH,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_XTTGS,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_XTTWH,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_XTTBH,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_XTTGS,   "Jf,Ji6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_XTTWH,   "Jf,Ji6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_XTTBH,   "Jf,Ji6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_XTTGS,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_XTTWH,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_XTTBH,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },	
{"sfppushc",   0, INSN_CLASS_XTTGS,   "",               MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },
{"sfppushc",   0, INSN_CLASS_XTTWH,   "Ji1",            MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },
{"sfppushc",   0, INSN_CLASS_XTTBH,   "Ji1",            MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },	
{"sfppopc",    0, INSN_CLASS_XTTGS,   "",               MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfppopc",    0, INSN_CLASS_XTTWH,   "Ji1",            MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfppopc",    0, INSN_CLASS_XTTBH,   "Ji1",            MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_XTTGS,   "Jg,Jf,Ji1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_XTTWH,   "Jg,Jf,Ji1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_XTTBH,   "Jg,Jf,Ji1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_XTTGS,   "Jh,Jg,Ji2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_XTTWH,   "Jh,Jg,Ji2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_XTTBH,   "Jh,Jg,Ji2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_XTTGS,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_XTTWH,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_XTTBH,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"sfpnop",     0, INSN_CLASS_XTTWH,   "",               MATCH_SFPWNOP,   MASK_SFPWNOP,   sfp_match_opcode, 0 },
{"sfpnop",     0, INSN_CLASS_XTTBH,   "",               MATCH_SFPWNOP,   MASK_SFPWNOP,   sfp_match_opcode, 0 },
{"ttincrwc",   0, INSN_CLASS_XTTGS,   "Jk1,Jk2,Jk3,Jk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttincrwc",   0, INSN_CLASS_XTTWH,   "Jk1,Jk2,Jk3,Jk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttincrwc",   0, INSN_CLASS_XTTBH,   "Jk1,Jk2,Jk3,Jk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttreplay",   0, INSN_CLASS_XTTWH,   "Jl1,Jl2,Jl3,Jl4",MATCH_SFPREPLAY, MASK_SFPREPLAY, sfp_match_opcode, 0 },
{"ttreplay",   0, INSN_CLASS_XTTBH,   "Jl1,Jl2,Jl3,Jl4",MATCH_SFPREPLAY, MASK_SFPREPLAY, sfp_match_opcode, 0 },
{"sfpxor",     0, INSN_CLASS_XTTWH,   "Jh,Jg",          MATCH_SFPXOR,    MASK_SFPXOR,    sfp_match_opcode, 0 },
{"sfpxor",     0, INSN_CLASS_XTTBH,   "Jh,Jg",          MATCH_SFPXOR,    MASK_SFPXOR,    sfp_match_opcode, 0 },	
{"sfpcast",    0, INSN_CLASS_XTTWH,   "Je,Jc,Ji2",      MATCH_SFPCAST,   MASK_SFPCAST,   sfp_match_opcode, 0 },
{"sfpcast",    0, INSN_CLASS_XTTBH,   "Je,Jc,Ji2",      MATCH_SFPCAST,   MASK_SFPCAST,   sfp_match_opcode, 0 },	
{"sfpshft2",   0, INSN_CLASS_XTTWH,   "Je,Jc,Ji2",      MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, 0 },
{"sfpshft2",   0, INSN_CLASS_XTTBH,   "Je,Jc,Ji2",      MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, 0 },
// FIXME: Something wrong here, (1) WH vs BH asymetry, and (2)
// disassembles to above.
{"sfpshft2",   0, INSN_CLASS_XTTWH,   "Je,Jc,Jf,Ji2",   MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, INSN_ALIAS },
{"sfpshft2",   0, INSN_CLASS_XTTBH,   "Je,Jc,Jf,Ji2",   MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, 0 },
{"sfpconfig",  0, INSN_CLASS_XTTWH,   "Jh,Jj,Ji7",      MATCH_SFPCONFIG, MASK_SFPCONFIG, sfp_match_opcode, 0 },
{"sfpconfig",  0, INSN_CLASS_XTTBH,   "Jh,Jj,Ji7",      MATCH_SFPCONFIG, MASK_SFPCONFIG, sfp_match_opcode, 0 },
{"sfpswap",    0, INSN_CLASS_XTTWH,   "Jh,Jg,Ji8",      MATCH_SFPSWAP,   MASK_SFPSWAP,   sfp_match_opcode, 0 },
{"sfpswap",    0, INSN_CLASS_XTTBH,   "Jh,Jg,Ji1",      MATCH_SFPSWAP,   MASK_SFPSWAP,    sfp_match_opcode, 0 },	
{"sfplutfp32", 0, INSN_CLASS_XTTWH,   "Je,Jo",          MATCH_SFPLUTFP32,MASK_SFPLUTFP32,sfp_match_opcode, 0 },
{"sfplutfp32", 0, INSN_CLASS_XTTBH,   "Je,Jo",          MATCH_SFPLUTFP32,MASK_SFPLUTFP32,sfp_match_opcode, 0 },
{"sfptransp",  0, INSN_CLASS_XTTWH,   "",               MATCH_SFPTRANSP, MASK_SFPTRANSP, sfp_match_opcode, 0 },
{"sfptransp",  0, INSN_CLASS_XTTBH,   "",               MATCH_SFPTRANSP, MASK_SFPTRANSP,sfp_match_opcode, 0 },
{"sfploadmacro",0,INSN_CLASS_XTTWH,  "Jd1,Jq,Jm1,Jp",   MATCH_SFPLDMACRO,MASK_SFPLDMACRO,sfp_match_opcode, 0 },
{"sfploadmacro",0,INSN_CLASS_XTTBH,   "Jd1,Jxa3,Jm1,Jxa2",MATCH_SFPLDMACRO,MASK_SFPLDMACRO,sfp_match_opcode, 0 },
{"sfpstochrnd",0, INSN_CLASS_XTTWH,   "Je,Jb,Jc,Ji1,Jr1,Jr2", MATCH_SFPSTOCH_RND,  MASK_SFPSTOCH_RND,  sfp_match_opcode, 0 },
{"sfpstochrnd",0, INSN_CLASS_XTTBH,   "Je,Jb,Jc,Ji1,Jr1,Jr2", MATCH_SFPSTOCH_RND,  MASK_SFPSTOCH_RND,  sfp_match_opcode, 0 },
{"sfparecip",  0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji1",   MATCH_SFPARECIP,  MASK_SFPARECIP,  sfp_match_opcode, INSN_ALIAS },
{"sfpgt",      0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji1",   MATCH_SFPGT,      MASK_SFPGT,  sfp_match_opcode, INSN_ALIAS },
{"sfpmul24",   0, INSN_CLASS_XTTBH,   "Je,Ja,Jb,Jc,Ji1", MATCH_SFPMUL24,   MASK_SFPMUL24,  sfp_match_opcode, INSN_ALIAS },
{"sfple",      0, INSN_CLASS_XTTBH,   "Jh,Jg,Jf,Ji1",   MATCH_SFPLE,      MASK_SFPLE,  sfp_match_opcode, INSN_ALIAS },


/* DMA Reg Instructions */
{"ttadddmareg",0, INSN_CLASS_XTTGS,  "Js4,Js3,Js2,Js1", MATCH_SFPADDDMAREG, MASK_SFPADDDMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttadddmareg",0, INSN_CLASS_XTTWH,  "Js4,Js3,Js2,Js1", MATCH_SFPADDDMAREG, MASK_SFPADDDMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttadddmareg",0, INSN_CLASS_XTTBH,  "Js4,Js3,Js2,Js1", MATCH_SFPADDDMAREG, MASK_SFPADDDMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsubdmareg",0, INSN_CLASS_XTTGS,  "Js4,Js3,Js2,Js1", MATCH_SFPSUB_DMAREG, MASK_SFPSUB_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsubdmareg",0, INSN_CLASS_XTTWH,  "Js4,Js3,Js2,Js1", MATCH_SFPSUB_DMAREG, MASK_SFPSUB_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsubdmareg",0, INSN_CLASS_XTTBH,  "Js4,Js3,Js2,Js1", MATCH_SFPSUB_DMAREG, MASK_SFPSUB_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttmuldmareg",0, INSN_CLASS_XTTGS,  "Js4,Js3,Js2,Js1", MATCH_SFPMUL_DMAREG, MASK_SFPMUL_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttmuldmareg",0, INSN_CLASS_XTTWH,  "Js4,Js3,Js2,Js1", MATCH_SFPMUL_DMAREG, MASK_SFPMUL_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttmuldmareg",0, INSN_CLASS_XTTBH,  "Js4,Js3,Js2,Js1", MATCH_SFPMUL_DMAREG, MASK_SFPMUL_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsetdmareg",0, INSN_CLASS_XTTGS,  "Js6,Js7,Js8,Js9", MATCH_SFPSET_DMAREG, MASK_SFPSET_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsetdmareg",0, INSN_CLASS_XTTWH,  "Js6,Js7,Js8,Js9", MATCH_SFPSET_DMAREG, MASK_SFPSET_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsetdmareg",0, INSN_CLASS_XTTBH,  "Js6,Js7,Js8,Js9", MATCH_SFPSET_DMAREG, MASK_SFPSET_DMAREG, sfp_match_opcode, INSN_ALIAS },	
{"ttshiftdmareg", 0, INSN_CLASS_XTTGS, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPSHIFT_DMAREG,  MASK_SFPSHIFT_DMAREG,  sfp_match_opcode, INSN_ALIAS },
{"ttshiftdmareg", 0, INSN_CLASS_XTTWH, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPSHIFT_DMAREG,  MASK_SFPSHIFT_DMAREG,  sfp_match_opcode, INSN_ALIAS },
{"ttshiftdmareg", 0, INSN_CLASS_XTTBH, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPSHIFT_DMAREG,  MASK_SFPSHIFT_DMAREG,  sfp_match_opcode, INSN_ALIAS },
{"ttcmpdmareg",   0, INSN_CLASS_XTTGS, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPCMP_DMAREG,    MASK_SFPCMP_DMAREG,    sfp_match_opcode, INSN_ALIAS },
{"ttcmpdmareg",   0, INSN_CLASS_XTTWH, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPCMP_DMAREG,    MASK_SFPCMP_DMAREG,    sfp_match_opcode, INSN_ALIAS },
{"ttcmpdmareg",   0, INSN_CLASS_XTTBH, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPCMP_DMAREG,    MASK_SFPCMP_DMAREG,    sfp_match_opcode, INSN_ALIAS },
{"ttbitwopdmareg",0, INSN_CLASS_XTTGS, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPBITWOP_DMAREG, MASK_SFPBITWOP_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttbitwopdmareg",0, INSN_CLASS_XTTWH, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPBITWOP_DMAREG, MASK_SFPBITWOP_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttbitwopdmareg",0, INSN_CLASS_XTTBH, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPBITWOP_DMAREG, MASK_SFPBITWOP_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrxy",    0, INSN_CLASS_XTTGS, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRXY, MASK_SFPADDRCRXY, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrxy",    0, INSN_CLASS_XTTWH, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRXY, MASK_SFPADDRCRXY, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrxy",    0, INSN_CLASS_XTTBH, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRXY, MASK_SFPADDRCRXY, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrzw",    0, INSN_CLASS_XTTGS, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRZW, MASK_SFPADDRCRZW, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrzw",    0, INSN_CLASS_XTTWH, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRZW, MASK_SFPADDRCRZW, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrzw",    0, INSN_CLASS_XTTBH, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRZW, MASK_SFPADDRCRZW, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s1",    0, INSN_CLASS_XTTGS, "Jss,Jsh,Jsj",         MATCH_SFPAPOOL3S1, MASK_SFPAPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s1",    0, INSN_CLASS_XTTWH, "Jss,Jsh,Jsi,Jsj",     MATCH_SFPAPOOL3S1, MASK_SFPAPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s1",    0, INSN_CLASS_XTTBH, "Jss,Jsh,Jsi,Jsj",     MATCH_SFPAPOOL3S1, MASK_SFPAPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s2",    0, INSN_CLASS_XTTGS, "Jss,Jsh,Jsj",         MATCH_SFPAPOOL3S2, MASK_SFPAPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s2",    0, INSN_CLASS_XTTWH, "Jss,Jsh,Jsi,Jsj",     MATCH_SFPAPOOL3S2, MASK_SFPAPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s2",    0, INSN_CLASS_XTTBH, "Jss,Jsh,Jsi,Jsj",     MATCH_SFPAPOOL3S2, MASK_SFPAPOOL3S2, sfp_match_opcode, INSN_ALIAS },	
{"ttatcas",       0, INSN_CLASS_XTTGS, "Jsk,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATCAS, MASK_SFPATCAS, sfp_match_opcode, INSN_ALIAS },
{"ttatcas",       0, INSN_CLASS_XTTWH, "Jsk,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATCAS, MASK_SFPATCAS, sfp_match_opcode, INSN_ALIAS },
{"ttatcas",       0, INSN_CLASS_XTTBH, "Jsk,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATCAS, MASK_SFPATCAS, sfp_match_opcode, INSN_ALIAS },
{"ttatgetm",      0, INSN_CLASS_XTTGS, "Jsr",                 MATCH_SFPATGETM, MASK_SFPATGETM, sfp_match_opcode, INSN_ALIAS },
{"ttatgetm",      0, INSN_CLASS_XTTWH, "Jsr",                 MATCH_SFPATGETM, MASK_SFPATGETM, sfp_match_opcode, INSN_ALIAS },
{"ttatgetm",      0, INSN_CLASS_XTTBH, "Jsr",                 MATCH_SFPATGETM, MASK_SFPATGETM, sfp_match_opcode, INSN_ALIAS },	
{"ttatincget",    0, INSN_CLASS_XTTGS, "Jsk,Jsm,Jsn,Jso,Jsp", MATCH_SFPATINCGET, MASK_SFPATINCGET, sfp_match_opcode, INSN_ALIAS },
{"ttatincget",    0, INSN_CLASS_XTTWH, "Jsk,Jsm,Jsn,Jso,Jsp", MATCH_SFPATINCGET, MASK_SFPATINCGET, sfp_match_opcode, INSN_ALIAS },
{"ttatincget",    0, INSN_CLASS_XTTBH, "Jsk,Jsm,Jsn,Jso,Jsp", MATCH_SFPATINCGET, MASK_SFPATINCGET, sfp_match_opcode, INSN_ALIAS },	
// FIXME: is w1 correct -- seems 15 might be the limit?
{"ttatincgetptr", 0, INSN_CLASS_XTTGS, "Jsk,Jsq,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATINCGETPTR, MASK_SFPATINCGETPTR, sfp_match_opcode, INSN_ALIAS },
{"ttatincgetptr", 0, INSN_CLASS_XTTWH, "Jsk,Jsq,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATINCGETPTR, MASK_SFPATINCGETPTR, sfp_match_opcode, INSN_ALIAS },
{"ttatincgetptr", 0, INSN_CLASS_XTTBH, "Jsk,Jsq,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATINCGETPTR, MASK_SFPATINCGETPTR, sfp_match_opcode, INSN_ALIAS },
{"ttatrelm",      0, INSN_CLASS_XTTGS, "Jsr",                 MATCH_SFPATRELM, MASK_SFPATRELM, sfp_match_opcode, INSN_ALIAS },
{"ttatrelm",      0, INSN_CLASS_XTTWH, "Jsr",                 MATCH_SFPATRELM, MASK_SFPATRELM, sfp_match_opcode, INSN_ALIAS },
{"ttatrelm",      0, INSN_CLASS_XTTBH, "Jsr",                 MATCH_SFPATRELM, MASK_SFPATRELM, sfp_match_opcode, INSN_ALIAS },
{"ttatswap",      0, INSN_CLASS_XTTGS, "Jsk,Jsm,Jso,Jsp",     MATCH_SFPATSWAP, MASK_SFPATSWAP, sfp_match_opcode, INSN_ALIAS },
{"ttatswap",      0, INSN_CLASS_XTTWH, "Jsk,Jsm,Jso,Jsp",     MATCH_SFPATSWAP, MASK_SFPATSWAP, sfp_match_opcode, INSN_ALIAS },
{"ttatswap",      0, INSN_CLASS_XTTBH, "Jsk,Jsm,Jso,Jsp",     MATCH_SFPATSWAP, MASK_SFPATSWAP, sfp_match_opcode, INSN_ALIAS },
{"ttcleardvalid", 0, INSN_CLASS_XTTGS, "Jss,Jst",             MATCH_SFPCLEARDVALID, MASK_SFPCLEARDVALID,sfp_match_opcode, INSN_ALIAS },
{"ttcleardvalid", 0, INSN_CLASS_XTTWH, "Jss,Jst",             MATCH_SFPCLEARDVALID, MASK_SFPCLEARDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttcleardvalid", 0, INSN_CLASS_XTTBH, "Jss,Jst",             MATCH_SFPCLEARDVALID, MASK_SFPCLEARDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttclrexphist",  0, INSN_CLASS_XTTGS, "",                    MATCH_SFPCLREXPHIST, MASK_SFPCLREXPHIST,sfp_match_opcode, INSN_ALIAS },
{"ttclrexphist",  0, INSN_CLASS_XTTWH, "",                    MATCH_SFPCLREXPHIST, MASK_SFPCLREXPHIST,sfp_match_opcode, INSN_ALIAS },
{"ttclrexphist",  0, INSN_CLASS_XTTBH, "",                    MATCH_SFPCLREXPHIST, MASK_SFPCLREXPHIST,sfp_match_opcode, INSN_ALIAS },	
{"ttconv3s1",     0, INSN_CLASS_XTTGS, "Jss,Jsu,Jsv,Jsw",     MATCH_SFPCONV3S1, MASK_SFPCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s1",     0, INSN_CLASS_XTTWH, "Jss,Jsu,Jsv,Jsw",     MATCH_SFPCONV3S1, MASK_SFPCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s1",     0, INSN_CLASS_XTTBH, "Jss,Jsu,Jxa4,Jxa5",   MATCH_SFPCONV3S1, MASK_SFPCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s2",     0, INSN_CLASS_XTTGS, "Jss,Jsu,Jsv,Jsw",     MATCH_SFPCONV3S2, MASK_SFPCONV3S2, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s2",     0, INSN_CLASS_XTTWH, "Jss,Jsu,Jsv,Jsw",     MATCH_SFPCONV3S2, MASK_SFPCONV3S2, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s2",     0, INSN_CLASS_XTTBH, "Jss,Jsu,Jxa4,Jxa5",   MATCH_SFPCONV3S2, MASK_SFPCONV3S2, sfp_match_opcode, INSN_ALIAS },
{"ttdmanop",      0, INSN_CLASS_XTTGS, "",                      MATCH_SFPDMANOP, MASK_SFPDMANOP,sfp_match_opcode, INSN_ALIAS },
{"ttdmanop",      0, INSN_CLASS_XTTWH, "",                      MATCH_SFPDMANOP, MASK_SFPDMANOP,sfp_match_opcode, INSN_ALIAS },
{"ttdmanop",      0, INSN_CLASS_XTTBH, "",                      MATCH_SFPDMANOP, MASK_SFPDMANOP,sfp_match_opcode, INSN_ALIAS },
{"ttdotpv",       0, INSN_CLASS_XTTGS, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPDOTPV, MASK_SFPDOTPV, sfp_match_opcode, INSN_ALIAS },
{"ttdotpv",       0, INSN_CLASS_XTTWH, "Jss,Jsx,Jsy,Jsz,Jsw",   MATCH_SFPDOTPV, MASK_SFPDOTPV, sfp_match_opcode, INSN_ALIAS },
{"ttdotpv",       0, INSN_CLASS_XTTBH, "Jss,Jsx,Jsy,Jxa0,Jxa5", MATCH_SFPDOTPV, MASK_SFPDOTPV, sfp_match_opcode, INSN_ALIAS },
// FIXME: The BH encodings use WH prefix -- but the whole
// distingishing there is unneeded
{"ttelwadd",      0, INSN_CLASS_XTTGS, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPELWADD, MASK_SFPELWADD, sfp_match_opcode, INSN_ALIAS },
{"ttelwadd",      0, INSN_CLASS_XTTWH, "Jss,Jsx,Jsy,Jsz,Jsw",   MATCH_SFPELWADD, MASK_SFPELWADD, sfp_match_opcode, INSN_ALIAS },
{"ttelwadd",      0, INSN_CLASS_XTTBH, "Jss,Jsx,Jsy,Jxa0,Jxa5", MATCH_SFPELWADD, MASK_SFPELWADD, sfp_match_opcode, INSN_ALIAS },
{"ttelwmul",      0, INSN_CLASS_XTTGS, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPELWMUL, MASK_SFPELWMUL, sfp_match_opcode, INSN_ALIAS },
{"ttelwmul",      0, INSN_CLASS_XTTWH, "Jss,Jsx,Jsy,Jsz,Jsw",   MATCH_SFPELWMUL, MASK_SFPELWMUL, sfp_match_opcode, INSN_ALIAS },
{"ttelwmul",      0, INSN_CLASS_XTTBH, "Jss,Jsx,Jsy,Jxa0,Jxa5", MATCH_SFPELWMUL, MASK_SFPELWMUL, sfp_match_opcode, INSN_ALIAS },	
{"ttelwsub",      0, INSN_CLASS_XTTGS, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPELWSUB, MASK_SFPELWSUB, sfp_match_opcode, INSN_ALIAS },
{"ttelwsub",      0, INSN_CLASS_XTTWH, "Jss,Jsx,Jsy,Jsz,Jsw",   MATCH_SFPELWSUB, MASK_SFPELWSUB, sfp_match_opcode, INSN_ALIAS },
{"ttelwsub",      0, INSN_CLASS_XTTBH, "Jss,Jsx,Jsy,Jxa0,Jxa5", MATCH_SFPELWSUB, MASK_SFPELWSUB, sfp_match_opcode, INSN_ALIAS },
{"ttflushdma",    0, INSN_CLASS_XTTGS, "Jt0",     MATCH_SFPFLUSHDMA, MASK_SFPFLUSHDMA, sfp_match_opcode, INSN_ALIAS },
{"ttflushdma",    0, INSN_CLASS_XTTWH, "Jt0",     MATCH_SFPFLUSHDMA, MASK_SFPFLUSHDMA, sfp_match_opcode, INSN_ALIAS },
{"ttflushdma",    0, INSN_CLASS_XTTBH, "Jt0",     MATCH_SFPFLUSHDMA, MASK_SFPFLUSHDMA, sfp_match_opcode, INSN_ALIAS },
{"ttgapool",      0, INSN_CLASS_XTTGS, "Jss,Jt1,Jw8,Jsj",     MATCH_SFPGAPOOL, MASK_SFPGAPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgapool",      0, INSN_CLASS_XTTWH, "Jss,Jt1,Jsz,Jt2,Jsj", MATCH_SFPGAPOOL, MASK_SFPGAPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgapool",      0, INSN_CLASS_XTTBH, "Jss,Jt1,Jsz,Jt2,Jsj", MATCH_SFPGAPOOL, MASK_SFPGAPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgatesrcrst",  0, INSN_CLASS_XTTGS, "Jt3,Jt4",             MATCH_SFPGATESRCRST, MASK_SFPGATESRCRST, sfp_match_opcode, INSN_ALIAS },
{"ttgatesrcrst",  0, INSN_CLASS_XTTWH, "Jt3,Jt4",             MATCH_SFPGATESRCRST, MASK_SFPGATESRCRST, sfp_match_opcode, INSN_ALIAS },
{"ttgatesrcrst",  0, INSN_CLASS_XTTBH, "Jt3,Jt4",             MATCH_SFPGATESRCRST, MASK_SFPGATESRCRST, sfp_match_opcode, INSN_ALIAS },
{"ttgmpool",      0, INSN_CLASS_XTTGS, "Jss,Jt1,Jw8,Jsw",     MATCH_SFPGMPOOL, MASK_SFPGMPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgmpool",      0, INSN_CLASS_XTTWH, "Jss,Jt1,Jsz,Jt2,Jsj", MATCH_SFPGMPOOL, MASK_SFPGMPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgmpool",      0, INSN_CLASS_XTTBH, "Jss,Jt1,Jsz,Jt2,Jsj", MATCH_SFPGMPOOL, MASK_SFPGMPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttincadcxy",    0, INSN_CLASS_XTTGS, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCXY, MASK_SFPINCADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttincadcxy",    0, INSN_CLASS_XTTWH, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCXY, MASK_SFPINCADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttincadcxy",    0, INSN_CLASS_XTTBH, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCXY, MASK_SFPINCADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttincadczw",    0, INSN_CLASS_XTTGS, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCZW, MASK_SFPINCADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttincadczw",    0, INSN_CLASS_XTTWH, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCZW, MASK_SFPINCADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttincadczw",    0, INSN_CLASS_XTTBH, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCZW, MASK_SFPINCADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttloadind",     0, INSN_CLASS_XTTGS, "Jt9,Jta,Jtb,Jso,Jsp", MATCH_SFPLOADIND, MASK_SFPLOADIND, sfp_match_opcode, INSN_ALIAS },
{"ttloadind",     0, INSN_CLASS_XTTWH, "Jt9,Jta,Jtb,Jso,Jsp", MATCH_SFPLOADIND, MASK_SFPLOADIND, sfp_match_opcode, INSN_ALIAS },
{"ttloadind",     0, INSN_CLASS_XTTBH, "Jt9,Jta,Jtb,Jso,Jsp", MATCH_SFPLOADIND, MASK_SFPLOADIND, sfp_match_opcode, INSN_ALIAS },
{"ttloadreg",     0, INSN_CLASS_XTTGS, "Jtc,Jtd",             MATCH_SFPLOADREG, MASK_SFPLOADREG, sfp_match_opcode, INSN_ALIAS },
{"ttloadreg",     0, INSN_CLASS_XTTWH, "Jtc,Jtd",             MATCH_SFPLOADREG, MASK_SFPLOADREG, sfp_match_opcode, INSN_ALIAS },
{"ttloadreg",     0, INSN_CLASS_XTTBH, "Jtc,Jtd",             MATCH_SFPLOADREG, MASK_SFPLOADREG, sfp_match_opcode, INSN_ALIAS },
{"ttmfconv3s1",   0, INSN_CLASS_XTTWH, "Jss,Jte,Jsv,Jsw",     MATCH_SFPMFCONV3S1, MASK_SFPMFCONV3S1, sfp_match_opcode, INSN_ALIAS },
// FIXME: mix of WH/BH prefixes
{"ttmfconv3s1",   0, INSN_CLASS_XTTBH, "Jss,Jte,Jxa4,Jxa5",   MATCH_SFPMFCONV3S1, MASK_SFPMFCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmop",         0, INSN_CLASS_XTTGS, "Jtf,Jtg,Jth",         MATCH_SFPMOP, MASK_SFPMOP, sfp_match_opcode, INSN_ALIAS },
{"ttmop",         0, INSN_CLASS_XTTWH, "Jtf,Jtg,Jth",         MATCH_SFPMOP, MASK_SFPMOP, sfp_match_opcode, INSN_ALIAS },
{"ttmop",         0, INSN_CLASS_XTTBH, "Jtf,Jtg,Jth",         MATCH_SFPMOP, MASK_SFPMOP, sfp_match_opcode, INSN_ALIAS },
{"ttmopcfg",      0, INSN_CLASS_XTTGS, "Jti",                 MATCH_SFPMOP_CFG, MASK_SFPMOP_CFG, sfp_match_opcode, INSN_ALIAS },
{"ttmopcfg",      0, INSN_CLASS_XTTWH, "Jti",                 MATCH_SFPMOP_CFG, MASK_SFPMOP_CFG, sfp_match_opcode, INSN_ALIAS },
{"ttmopcfg",      0, INSN_CLASS_XTTBH, "Jti",                 MATCH_SFPMOP_CFG, MASK_SFPMOP_CFG, sfp_match_opcode, INSN_ALIAS },
{"ttmova2d",      0, INSN_CLASS_XTTGS, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVA2D, MASK_SFPMOVA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmova2d",      0, INSN_CLASS_XTTWH, "Jtj,Jtk,Jsv,Jtl,Jtm",   MATCH_SFPMOVA2D, MASK_SFPMOVA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmova2d",      0, INSN_CLASS_XTTBH, "Jtj,Jtk,Jxa4,Jxa6,Jtm", MATCH_SFPMOVA2D, MASK_SFPMOVA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2a",      0, INSN_CLASS_XTTGS, "Jtn,Jsv,Jtl,Jto",       MATCH_SFPMOVB2A, MASK_SFPMOVB2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2a",      0, INSN_CLASS_XTTWH, "Jtn,Jsv,Jtl,Jto",       MATCH_SFPMOVB2A, MASK_SFPMOVB2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2a",      0, INSN_CLASS_XTTBH, "Jtn,Jxa7,Jxa6,Jto",     MATCH_SFPMOVB2A, MASK_SFPMOVB2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2d",      0, INSN_CLASS_XTTGS, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVB2D, MASK_SFPMOVB2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2d",      0, INSN_CLASS_XTTWH, "Jtj,Jtk,Jsv,Jtl,Jtm",   MATCH_SFPMOVB2D, MASK_SFPMOVB2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2d",      0, INSN_CLASS_XTTBH, "Jtj,Jtk,Jxa4,Jtl,Jxaa", MATCH_SFPMOVB2D, MASK_SFPMOVB2D, sfp_match_opcode, INSN_ALIAS },	
{"ttmovd2a",      0, INSN_CLASS_XTTGS, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVD2A, MASK_SFPMOVD2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2a",      0, INSN_CLASS_XTTWH, "Jtj,Jtk,Jsv,Jtl,Jtm",   MATCH_SFPMOVD2A, MASK_SFPMOVD2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2a",      0, INSN_CLASS_XTTBH, "Jtj,Jtk,Jxa4,Jxa6,Jtm", MATCH_SFPMOVD2A, MASK_SFPMOVD2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2b",      0, INSN_CLASS_XTTGS, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVD2B, MASK_SFPMOVD2B, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2b",      0, INSN_CLASS_XTTWH, "Jtj,Jtk,Jsv,Jtl,Jtm",   MATCH_SFPMOVD2B, MASK_SFPMOVD2B, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2b",      0, INSN_CLASS_XTTBH, "Jtj,Jtk,Jxa4,Jxa6,Jtm", MATCH_SFPMOVD2B, MASK_SFPMOVD2B, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbga2d",   0, INSN_CLASS_XTTGS, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVDBGA2D, MASK_SFPMOVDBGA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbga2d",   0, INSN_CLASS_XTTWH, "Jtj,Jtk,Jsv,Jtl,Jtm",   MATCH_SFPMOVDBGA2D, MASK_SFPMOVDBGA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbga2d",   0, INSN_CLASS_XTTBH, "Jtj,Jtk,Jxa4,Jxa6,Jtm", MATCH_SFPMOVDBGA2D, MASK_SFPMOVDBGA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s1",    0, INSN_CLASS_XTTGS, "Jss,Jsh,Jsj",     MATCH_SFPMPOOL3S1, MASK_SFPMPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s1",    0, INSN_CLASS_XTTWH, "Jss,Jsh,Jsi,Jsj", MATCH_SFPMPOOL3S1, MASK_SFPMPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s1",    0, INSN_CLASS_XTTBH, "Jss,Jsh,Jsi,Jsj", MATCH_SFPMPOOL3S1, MASK_SFPMPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s2",    0, INSN_CLASS_XTTGS, "Jss,Jsh,Jsw",     MATCH_SFPMPOOL3S2, MASK_SFPMPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s2",    0, INSN_CLASS_XTTWH, "Jss,Jsh,Jsi,Jsj", MATCH_SFPMPOOL3S2, MASK_SFPMPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s2",    0, INSN_CLASS_XTTBH, "Jss,Jsh,Jsi,Jsj", MATCH_SFPMPOOL3S2, MASK_SFPMPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttmvmul",       0, INSN_CLASS_XTTGS, "Jss,Jt1,Jsz,Jsw",     MATCH_SFPMVMUL, MASK_SFPMVMUL, sfp_match_opcode, INSN_ALIAS },
{"ttmvmul",       0, INSN_CLASS_XTTWH, "Jss,Jt1,Jsz,Jsw",     MATCH_SFPMVMUL, MASK_SFPMVMUL, sfp_match_opcode, INSN_ALIAS },
{"ttmvmul",       0, INSN_CLASS_XTTBH, "Jss,Jt1,Jxa0,Jxa5",   MATCH_SFPMVMUL, MASK_SFPMVMUL, sfp_match_opcode, INSN_ALIAS },	
{"ttpacr",        0, INSN_CLASS_XTTGS, "Jtp,Jtq,Jty,Jtr,Jts,Jtt,Jtu", MATCH_SFP_PACR, MASK_SFP_PACR, sfp_match_opcode, INSN_ALIAS },
{"ttpacr",        0, INSN_CLASS_XTTWH, "Jtp,Jtq,Jty,Jtr,Jts,Jtt,Jtu", MATCH_SFP_PACR, MASK_SFP_PACR, sfp_match_opcode, INSN_ALIAS },
{"ttpacr",        0, INSN_CLASS_XTTBH, "Jxab,Jxac,Jxad,Jxae,Jxaf,Jxag,Jxah,Jxai,Jxaj,Jxak,Jxal,Jxam", MATCH_SFP_PACR, MASK_SFP_PACR, sfp_match_opcode, INSN_ALIAS },
{"ttpacrsetreg",  0, INSN_CLASS_XTTWH, "Jtv,Jtw,Jtx,Jty,Jtz,Ju0,Jtu", MATCH_SFP_PACR_SETREG, MASK_SFP_PACR_SETREG, sfp_match_opcode, INSN_ALIAS },
{"ttpacrsetreg",  0, INSN_CLASS_XTTBH, "Jxan,Jxao,Jxap,Jxaq,Jxar,Jxas,Jxal,Jxam", MATCH_SFP_PACR_SETREG, MASK_SFP_PACR_SETREG, sfp_match_opcode, INSN_ALIAS },
{"ttrareb",       0, INSN_CLASS_XTTGS, "",                MATCH_SFP_RAREB, MASK_SFP_RAREB, sfp_match_opcode, INSN_ALIAS },
{"ttrareb",       0, INSN_CLASS_XTTWH, "",                MATCH_SFP_RAREB, MASK_SFP_RAREB, sfp_match_opcode, INSN_ALIAS },
{"ttrareb",       0, INSN_CLASS_XTTBH, "",                MATCH_SFP_RAREB, MASK_SFP_RAREB, sfp_match_opcode, INSN_ALIAS },
{"ttrdcfg",       0, INSN_CLASS_XTTGS, "Ju1,Ju2",         MATCH_SFP_RDCFG, MASK_SFP_RDCFG,sfp_match_opcode, INSN_ALIAS },
{"ttrdcfg",       0, INSN_CLASS_XTTWH, "Ju1,Ju2",         MATCH_SFP_RDCFG, MASK_SFP_RDCFG,sfp_match_opcode, INSN_ALIAS },
{"ttrdcfg",       0, INSN_CLASS_XTTBH, "Ju1,Ju2",         MATCH_SFP_RDCFG, MASK_SFP_RDCFG,sfp_match_opcode, INSN_ALIAS },
{"ttreg2flop",    0, INSN_CLASS_XTTGS, "Jt9,Ju3,Ju4,Ju5,Ju6,Ju7", MATCH_SFP_REG2FLOP, MASK_SFP_REG2FLOP, sfp_match_opcode, INSN_ALIAS },
{"ttreg2flop",    0, INSN_CLASS_XTTWH, "Jt9,Ju3,Ju4,Ju5,Ju6,Ju7", MATCH_SFP_REG2FLOP, MASK_SFP_REG2FLOP, sfp_match_opcode, INSN_ALIAS },
{"ttreg2flop",    0, INSN_CLASS_XTTBH, "Jt9,Ju3,Ju4,Ju5,Ju6,Ju7", MATCH_SFP_REG2FLOP, MASK_SFP_REG2FLOP, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib0",     0, INSN_CLASS_XTTWH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB0, MASK_SFP_RMWCIB0, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib0",     0, INSN_CLASS_XTTBH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB0, MASK_SFP_RMWCIB0, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib1",     0, INSN_CLASS_XTTWH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB1, MASK_SFP_RMWCIB1, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib1",     0, INSN_CLASS_XTTBH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB1, MASK_SFP_RMWCIB1, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib2",     0, INSN_CLASS_XTTWH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB2, MASK_SFP_RMWCIB2, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib2",     0, INSN_CLASS_XTTBH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB2, MASK_SFP_RMWCIB2, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib3",     0, INSN_CLASS_XTTWH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB3, MASK_SFP_RMWCIB3, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib3",     0, INSN_CLASS_XTTBH, "Juc,Jud,Jue",     MATCH_SFP_RMWCIB3, MASK_SFP_RMWCIB3, sfp_match_opcode, INSN_ALIAS },
{"ttrstdma",      0, INSN_CLASS_XTTGS, "",                MATCH_SFP_RSTDMA, MASK_SFP_RSTDMA,sfp_match_opcode, INSN_ALIAS },
{"ttrstdma",      0, INSN_CLASS_XTTWH, "",                MATCH_SFP_RSTDMA, MASK_SFP_RSTDMA,sfp_match_opcode, INSN_ALIAS },
{"ttrstdma",      0, INSN_CLASS_XTTBH, "",                MATCH_SFP_RSTDMA, MASK_SFP_RSTDMA,sfp_match_opcode, INSN_ALIAS },

{"ttsemget",      0, INSN_CLASS_XTTGS, "Juf",             MATCH_SFP_SEMGET, MASK_SFP_SEMGET,sfp_match_opcode, INSN_ALIAS },
{"ttsemget",      0, INSN_CLASS_XTTWH, "Juf",             MATCH_SFP_SEMGET, MASK_SFP_SEMGET,sfp_match_opcode, INSN_ALIAS },
{"ttsemget",      0, INSN_CLASS_XTTBH, "Juf",             MATCH_SFP_SEMGET, MASK_SFP_SEMGET,sfp_match_opcode, INSN_ALIAS },
{"ttseminit",     0, INSN_CLASS_XTTGS, "Jug,Juh,Jui",     MATCH_SFP_SEMINIT, MASK_SFP_SEMINIT, sfp_match_opcode, INSN_ALIAS },
{"ttseminit",     0, INSN_CLASS_XTTWH, "Jug,Juh,Jui",     MATCH_SFP_SEMINIT, MASK_SFP_SEMINIT, sfp_match_opcode, INSN_ALIAS },
{"ttseminit",     0, INSN_CLASS_XTTBH, "Jug,Juh,Jui",     MATCH_SFP_SEMINIT, MASK_SFP_SEMINIT, sfp_match_opcode, INSN_ALIAS },
{"ttsempost",     0, INSN_CLASS_XTTGS, "Juf",             MATCH_SFP_SEMPOST, MASK_SFP_SEMPOST, sfp_match_opcode, INSN_ALIAS },
{"ttsempost",     0, INSN_CLASS_XTTWH, "Juf",             MATCH_SFP_SEMPOST, MASK_SFP_SEMPOST, sfp_match_opcode, INSN_ALIAS },
{"ttsempost",     0, INSN_CLASS_XTTBH, "Juf",             MATCH_SFP_SEMPOST, MASK_SFP_SEMPOST, sfp_match_opcode, INSN_ALIAS },
{"ttsemwait",     0, INSN_CLASS_XTTGS, "Jw6,Jw7,Jul",     MATCH_SFP_SEMWAIT, MASK_SFP_SEMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttsemwait",     0, INSN_CLASS_XTTWH, "Juj,Juk,Jul",     MATCH_SFP_SEMWAIT, MASK_SFP_SEMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttsemwait",     0, INSN_CLASS_XTTBH, "Juj,Juk,Jul",     MATCH_SFP_SEMWAIT, MASK_SFP_SEMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttsetadc",      0, INSN_CLASS_XTTGS, "Jsa,Jum,Jun,Juo", MATCH_SFP_SETADC, MASK_SFP_SETADC, sfp_match_opcode, INSN_ALIAS },
{"ttsetadc",      0, INSN_CLASS_XTTWH, "Jsa,Jum,Jun,Juo", MATCH_SFP_SETADC, MASK_SFP_SETADC, sfp_match_opcode, INSN_ALIAS },
{"ttsetadc",      0, INSN_CLASS_XTTBH, "Jsa,Jum,Jun,Juo", MATCH_SFP_SETADC, MASK_SFP_SETADC, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxx",    0, INSN_CLASS_XTTGS, "Jsa,Jup,Juq",     MATCH_SFP_SETADCXX, MASK_SFP_SETADCXX, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxx",    0, INSN_CLASS_XTTWH, "Jsa,Jup,Juq",     MATCH_SFP_SETADCXX, MASK_SFP_SETADCXX, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxx",    0, INSN_CLASS_XTTBH, "Jsa,Jup,Juq",     MATCH_SFP_SETADCXX, MASK_SFP_SETADCXX, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxy",    0, INSN_CLASS_XTTGS, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCXY, MASK_SFP_SETADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxy",    0, INSN_CLASS_XTTWH, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCXY, MASK_SFP_SETADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxy",    0, INSN_CLASS_XTTBH, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCXY, MASK_SFP_SETADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttsetadczw",    0, INSN_CLASS_XTTGS, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCZW, MASK_SFP_SETADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttsetadczw",    0, INSN_CLASS_XTTWH, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCZW, MASK_SFP_SETADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttsetadczw",    0, INSN_CLASS_XTTBH, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCZW, MASK_SFP_SETADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh",   0, INSN_CLASS_XTTGS, "Jus,Jut",         MATCH_SFP_SETASHRMH, MASK_SFP_SETASHRMH, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh",   0, INSN_CLASS_XTTWH, "Jus,Jut",         MATCH_SFP_SETASHRMH, MASK_SFP_SETASHRMH, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh",   0, INSN_CLASS_XTTBH, "Jus,Jut",         MATCH_SFP_SETASHRMH, MASK_SFP_SETASHRMH, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh0",  0, INSN_CLASS_XTTGS, "Jus,Jut",         MATCH_SFP_SETASHRMH0, MASK_SFP_SETASHRMH0, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh0",  0, INSN_CLASS_XTTWH, "Jus,Jut",         MATCH_SFP_SETASHRMH0, MASK_SFP_SETASHRMH0, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh0",  0, INSN_CLASS_XTTBH, "Jus,Jut",         MATCH_SFP_SETASHRMH0, MASK_SFP_SETASHRMH0, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh1",  0, INSN_CLASS_XTTGS, "Jus,Jut",         MATCH_SFP_SETASHRMH1, MASK_SFP_SETASHRMH1, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh1",  0, INSN_CLASS_XTTWH, "Jus,Jut",         MATCH_SFP_SETASHRMH1, MASK_SFP_SETASHRMH1, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh1",  0, INSN_CLASS_XTTBH, "Jus,Jut",         MATCH_SFP_SETASHRMH1, MASK_SFP_SETASHRMH1, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmv",   0, INSN_CLASS_XTTGS, "Juu",             MATCH_SFP_SETASHRMV, MASK_SFP_SETASHRMV, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmv",   0, INSN_CLASS_XTTWH, "Juu",             MATCH_SFP_SETASHRMV, MASK_SFP_SETASHRMV, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmv",   0, INSN_CLASS_XTTBH, "Juu",             MATCH_SFP_SETASHRMV, MASK_SFP_SETASHRMV, sfp_match_opcode, INSN_ALIAS },
{"ttsetc16",      0, INSN_CLASS_XTTGS, "Juv,Juw",         MATCH_SFP_SETC16, MASK_SFP_SETC16, sfp_match_opcode, INSN_ALIAS },
{"ttsetc16",      0, INSN_CLASS_XTTWH, "Juv,Juw",         MATCH_SFP_SETC16, MASK_SFP_SETC16, sfp_match_opcode, INSN_ALIAS },
{"ttsetc16",      0, INSN_CLASS_XTTBH, "Juv,Juw",         MATCH_SFP_SETC16, MASK_SFP_SETC16, sfp_match_opcode, INSN_ALIAS },
{"ttsetdvalid",   0, INSN_CLASS_XTTGS, "Juw",             MATCH_SFP_SETDVALID, MASK_SFP_SETDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttsetdvalid",   0, INSN_CLASS_XTTWH, "Juw",             MATCH_SFP_SETDVALID, MASK_SFP_SETDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttsetdvalid",   0, INSN_CLASS_XTTBH, "Juw",             MATCH_SFP_SETDVALID, MASK_SFP_SETDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttsetibrwc",    0, INSN_CLASS_XTTWH, "Jt5,Juy,Juz",     MATCH_SFP_SETIBRWC, MASK_SFP_SETIBRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetibrwc",    0, INSN_CLASS_XTTBH, "Jt5,Juy,Juz",     MATCH_SFP_SETIBRWC, MASK_SFP_SETIBRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetpkedgof",  0, INSN_CLASS_XTTGS, "Jv0,Jv1,Jv2,Jw2", MATCH_SFP_SETPKEDGOF, MASK_SFP_SETPKEDGOF, sfp_match_opcode, INSN_ALIAS },
{"ttsetpkedgof",  0, INSN_CLASS_XTTWH, "Jv0,Jv1,Jv2,Jw2", MATCH_SFP_SETPKEDGOF, MASK_SFP_SETPKEDGOF, sfp_match_opcode, INSN_ALIAS },
{"ttsetpkedgof",  0, INSN_CLASS_XTTBH, "Jv0,Jv1,Jv2,Jw2", MATCH_SFP_SETPKEDGOF, MASK_SFP_SETPKEDGOF, sfp_match_opcode, INSN_ALIAS },
{"ttsetrwc",      0, INSN_CLASS_XTTGS, "Jv3,Jt5,Jt6,Jt7,Jt8,Jur", MATCH_SFP_SETRWC, MASK_SFP_SETRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetrwc",      0, INSN_CLASS_XTTWH, "Jv3,Jt5,Jt6,Jt7,Jt8,Jur", MATCH_SFP_SETRWC, MASK_SFP_SETRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetrwc",      0, INSN_CLASS_XTTBH, "Jv3,Jt5,Jt6,Jt7,Jt8,Jur", MATCH_SFP_SETRWC, MASK_SFP_SETRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsfploadmacro",0, INSN_CLASS_XTTWH, "Jv4,Jv5,Jv6,Jv7", MATCH_SFP_SFPLOADMACRO, MASK_SFP_SFPLOADMACRO, sfp_match_opcode, INSN_ALIAS },
{"ttsfploadmacro",0, INSN_CLASS_XTTBH, "Jv4,Jv5,Js2,Js1", MATCH_SFP_SFPLOADMACRO, MASK_SFP_SFPLOADMACRO, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxa",     0, INSN_CLASS_XTTGS, "Jv8,Jv9",         MATCH_SFPSHIFTXA, MASK_SFPSHIFTXA, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxa",     0, INSN_CLASS_XTTWH, "Jv8,Jv9",         MATCH_SFPSHIFTXA, MASK_SFPSHIFTXA, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxa",     0, INSN_CLASS_XTTBH, "Jv8,Jv9",         MATCH_SFPSHIFTXA, MASK_SFPSHIFTXA, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxb",     0, INSN_CLASS_XTTWH, "Jtp,Jva,Jvb",     MATCH_SFPSHIFTXB, MASK_SFPSHIFTXB, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxb",     0, INSN_CLASS_XTTBH, "Jxat,Jxau,Jvb",   MATCH_SFPSHIFTXB, MASK_SFPSHIFTXB, sfp_match_opcode, INSN_ALIAS },
{"ttstallwait",   0, INSN_CLASS_XTTGS, "Jw6,Jsg",         MATCH_SFPSTALLWAIT, MASK_SFPSTALLWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstallwait",   0, INSN_CLASS_XTTWH, "Juj,Jvc",         MATCH_SFPSTALLWAIT, MASK_SFPSTALLWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstallwait",   0, INSN_CLASS_XTTBH, "Juj,Jvc",         MATCH_SFPSTALLWAIT, MASK_SFPSTALLWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstoreind",    0, INSN_CLASS_XTTGS, "Jsk,Jvd,Jve,Jvf,Jtb,Jso,Jsp", MATCH_SFPSTOREIND, MASK_SFPSTOREIND, sfp_match_opcode, INSN_ALIAS },
{"ttstoreind",    0, INSN_CLASS_XTTWH, "Jsk,Jvd,Jve,Jvf,Jtb,Jso,Jsp", MATCH_SFPSTOREIND, MASK_SFPSTOREIND, sfp_match_opcode, INSN_ALIAS },
{"ttstoreind",    0, INSN_CLASS_XTTBH, "Jsk,Jvd,Jve,Jvf,Jtb,Jso,Jsp", MATCH_SFPSTOREIND, MASK_SFPSTOREIND, sfp_match_opcode, INSN_ALIAS },
{"ttstorereg",    0, INSN_CLASS_XTTGS, "Jtc,Jtd",         MATCH_SFPSTOREREG, MASK_SFPSTOREREG, sfp_match_opcode, INSN_ALIAS },
{"ttstorereg",    0, INSN_CLASS_XTTWH, "Jtc,Jtd",         MATCH_SFPSTOREREG, MASK_SFPSTOREREG, sfp_match_opcode, INSN_ALIAS },
{"ttstorereg",    0, INSN_CLASS_XTTBH, "Jtc,Jtd",         MATCH_SFPSTOREREG, MASK_SFPSTOREREG, sfp_match_opcode, INSN_ALIAS },
{"tttbufcmd",     0, INSN_CLASS_XTTWH, "",                MATCH_SFPTBUFCMD, MASK_SFPTBUFCMD, sfp_match_opcode, INSN_ALIAS },
{"tttbufcmd",     0, INSN_CLASS_XTTBH, "",                MATCH_SFPTBUFCMD, MASK_SFPTBUFCMD, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrca",   0, INSN_CLASS_XTTGS, "",                MATCH_SFPTRNSPSRCA, MASK_SFPTRNSPSRCA, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrca",   0, INSN_CLASS_XTTWH, "",                MATCH_SFPTRNSPSRCA, MASK_SFPTRNSPSRCA, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrca",   0, INSN_CLASS_XTTBH, "",                MATCH_SFPTRNSPSRCA, MASK_SFPTRNSPSRCA, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrcb",   0, INSN_CLASS_XTTWH, "",                MATCH_SFPTRNSPSRCB, MASK_SFPTRNSPSRCB, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrcb",   0, INSN_CLASS_XTTBH, "",                MATCH_SFPTRNSPSRCB, MASK_SFPTRNSPSRCB, sfp_match_opcode, INSN_ALIAS },
{"ttunpacr",      0, INSN_CLASS_XTTGS, "Jvg,Jvh,Jvi,Jvj,Jvk,Jtr,Jvl,Jvm,Jvn,Jvo,Jvp,Jvq,Jt4", MATCH_SFPUNPACR, MASK_SFPUNPACR, sfp_match_opcode, INSN_ALIAS },
{"ttunpacr",      0, INSN_CLASS_XTTWH, "Jvg,Jvh,Jvi,Jvj,Jvk,Jtr,Jvl,Jvm,Jvn,Jvo,Jvp,Jvq,Jt4", MATCH_SFPUNPACR, MASK_SFPUNPACR, sfp_match_opcode, INSN_ALIAS },
{"ttunpacr",      0, INSN_CLASS_XTTBH, "Jxba,Jxbb,Jxbc,Jxbd,Jxbe,Jxbf,Jxbg,Jxbh,Jxbi,Jxbj,Jxbk,Jxbl,Jxam", MATCH_SFPUNPACR, MASK_SFPUNPACR, sfp_match_opcode, INSN_ALIAS },
{"ttunpacrnop",   0, INSN_CLASS_XTTGS, "Jvg,Jvr",         MATCH_SFPUNPACR_NOP, MASK_SFPUNPACR_NOP, sfp_match_opcode, INSN_ALIAS },
{"ttunpacrnop",   0, INSN_CLASS_XTTWH, "Jvg,Jvr",         MATCH_SFPUNPACR_NOP, MASK_SFPUNPACR_NOP, sfp_match_opcode, INSN_ALIAS },
{"ttunpacrnop",   0, INSN_CLASS_XTTBH, "Jxbm,Jxbn,Jxbo,Jxbp,Jxbq,Jxbr,Jxbs,Jxbt,Jxbu", MATCH_SFPUNPACR_NOP, MASK_SFPUNPACR_NOP, sfp_match_opcode, INSN_ALIAS },
{"ttwrcfg",       0, INSN_CLASS_XTTGS, "Ju1,Jvs,Jvt",     MATCH_SFPWRCFG, MASK_SFPWRCFG, sfp_match_opcode, INSN_ALIAS },
{"ttwrcfg",       0, INSN_CLASS_XTTWH, "Ju1,Jvs,Jvt",     MATCH_SFPWRCFG, MASK_SFPWRCFG, sfp_match_opcode, INSN_ALIAS },
{"ttwrcfg",       0, INSN_CLASS_XTTBH, "Ju1,Jvs,Jvt",     MATCH_SFPWRCFG, MASK_SFPWRCFG, sfp_match_opcode, INSN_ALIAS },
{"ttxmov",        0, INSN_CLASS_XTTGS, "Jvu,Jvv",         MATCH_SFPXMOV, MASK_SFPXMOV, sfp_match_opcode, INSN_ALIAS },
{"ttxmov",        0, INSN_CLASS_XTTWH, "Jvu,Jvv",         MATCH_SFPXMOV, MASK_SFPXMOV, sfp_match_opcode, INSN_ALIAS },
{"ttxmov",        0, INSN_CLASS_XTTBH, "Jvu,Jvv",         MATCH_SFPXMOV, MASK_SFPXMOV, sfp_match_opcode, INSN_ALIAS },
{"ttzeroacc",     0, INSN_CLASS_XTTGS, "Jvw,Jsz,Jsw",     MATCH_SFPZEROACC, MASK_SFPZEROACC, sfp_match_opcode, INSN_ALIAS },
{"ttzeroacc",     0, INSN_CLASS_XTTWH, "Jvw,Jsz,Jsw",     MATCH_SFPZEROACC, MASK_SFPZEROACC, sfp_match_opcode, INSN_ALIAS },
{"ttzeroacc",     0, INSN_CLASS_XTTBH, "Jvw,Jxc0,Jxc1,Jxc2,Jxc3", MATCH_SFPZEROACC, MASK_SFPZEROACC, sfp_match_opcode, INSN_ALIAS },
{"ttzerosrc",     0, INSN_CLASS_XTTGS, "Jvx,Jvy,Jvz,Jw0", MATCH_SFPZEROSRC, MASK_SFPZEROSRC, sfp_match_opcode, INSN_ALIAS },
{"ttzerosrc",     0, INSN_CLASS_XTTWH, "Jvx,Jvy,Jvz,Jw0", MATCH_SFPZEROSRC, MASK_SFPZEROSRC, sfp_match_opcode, INSN_ALIAS },
{"ttzerosrc",     0, INSN_CLASS_XTTBH, "Jvx,Jvy,Jvz,Jw0", MATCH_SFPZEROSRC, MASK_SFPZEROSRC, sfp_match_opcode, INSN_ALIAS },
{"ttcfgshiftmask",0, INSN_CLASS_XTTBH, "Jxav,Jxaw,Jxax,Jxay,Jxaz,Jxbv", MATCH_SFPCFGSHIFTMASK, MASK_SFPCFGSHIFTMASK, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbgb2d",   0, INSN_CLASS_XTTBH, "Jtj,Jtk,Jxa4,Jxc4,Jxaa", MATCH_SFPMOVDBGB2D, MASK_SFPMOVDBGB2D, sfp_match_opcode, INSN_ALIAS },
{"ttresourcedecl",0, INSN_CLASS_XTTBH, "Jxbw,Jxbx,Jxby",        MATCH_SFPRESOURCEDECL, MASK_SFPRESOURCEDECL, sfp_match_opcode, INSN_ALIAS },
{"ttstreamwait",  0, INSN_CLASS_XTTBH, "Juj,Jxbz,Jxb0,Jxb1",    MATCH_SFPSTREAMWAIT, MASK_SFPSTREAMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstreamwrcfg", 0, INSN_CLASS_XTTBH, "Jxb2,Jxb3,Jxb4",        MATCH_SFPSTREAMWRCFG, MASK_SFPSTREAMWRCFG, sfp_match_opcode, INSN_ALIAS },

#endif  // RISCV_OPC_SFPU_INSNS_H
