#ifndef RISCV_OPC_SFPU_INSNS_H
#define RISCV_OPC_SFPU_INSNS_H

/* SFPU Gray Skull Instructions.  */
{"sfpload",    0, INSN_CLASS_I_Y,   "Jd1,Jn,Jm1",     MATCH_SFPLOAD,   MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfpload",    0, INSN_CLASS_I_W,   "wd1,wq,wm1,wp",  MATCH_SFPLOAD,   MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfpload",    0, INSN_CLASS_I_U,   "ld1,lxa3,lm1,lxa2",MATCH_SFPLOAD, MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_I_Y,   "Jd1,Jn,Jm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_I_W,   "wd1,wn,wm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_I_U,   "ld1,ln,lm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },	
{"sfpstore",   0, INSN_CLASS_I_Y,   "Jn,Jd2,Jm2",     MATCH_SFPSTORE,  MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },
{"sfpstore",   0, INSN_CLASS_I_W,   "wq,wd2,wm1,wp",  MATCH_SFPSTORE,  MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },
{"sfpstore",   0, INSN_CLASS_I_U,   "lxa3,ld2,lm1,lxa2",MATCH_SFPSTORE,MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },	
{"sfplut",     0, INSN_CLASS_I_Y,   "Jd1,Jm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },
{"sfplut",     0, INSN_CLASS_I_W,   "wd1,wm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },
{"sfplut",     0, INSN_CLASS_I_U,   "ld1,lm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },	
{"sfpmuli",    0, INSN_CLASS_I_Y,   "Jh,Jj,Ji3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },
{"sfpmuli",    0, INSN_CLASS_I_W,   "wh,wj,wi3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },
{"sfpmuli",    0, INSN_CLASS_I_U,   "lh,lj,li3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },	
{"sfpaddi",    0, INSN_CLASS_I_Y,   "Jh,Jj,Ji3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },
{"sfpaddi",    0, INSN_CLASS_I_W,   "wh,wj,wi3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },
{"sfpaddi",    0, INSN_CLASS_I_U,   "lh,lj,li3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },	
{"sfpdivp2",   0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },
{"sfpdivp2",   0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },
{"sfpdivp2",   0, INSN_CLASS_I_U,   "lh,lg,lf,li2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },	
{"sfpexexp",   0, INSN_CLASS_I_Y,   "Jh,Jg,Ji4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },
{"sfpexexp",   0, INSN_CLASS_I_W,   "wh,wg,wi4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },
{"sfpexexp",   0, INSN_CLASS_I_U,   "lh,lg,li4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },	
{"sfpexman",   0, INSN_CLASS_I_Y,   "Jh,Jg,Ji2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },
{"sfpexman",   0, INSN_CLASS_I_W,   "wh,wg,wi2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },
{"sfpexman",   0, INSN_CLASS_I_U,   "lh,lg,li2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },	
{"sfpiadd",    0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },
{"sfpiadd",    0, INSN_CLASS_I_W,   "wh,wg,wf,wi5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },
{"sfpiadd",    0, INSN_CLASS_I_U,   "lh,lg,lf,li5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },	
{"sfpshft",    0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },
{"sfpshft",    0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },
{"sfpshft",    0, INSN_CLASS_I_U,   "lh,lg,lf,li2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },	
{"sfpabs",     0, INSN_CLASS_I_Y,   "Jh,Jg,Ji2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpabs",     0, INSN_CLASS_I_W,   "wh,wg,wi2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpabs",     0, INSN_CLASS_I_U,   "lh,lg,li2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_I_Y,   "Jh,Jg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_I_U,   "lh,lg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_I_Y,   "Jh,Jg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_I_U,   "lh,lg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_I_Y,   "Jh,Jg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_I_U,   "lh,lg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_I_Y,   "Jh,Jg,Ji6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_I_W,   "wh,wg,wi6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_I_U,   "lh,lg,li6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_I_U,   "lh,lg,lf,li2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_I_U,   "lh,lg,lf,li2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_I_U,   "lh,lg,lf,li2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_I_Y,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_I_W,   "we,wa,wb,wc,wo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_I_U,   "le,la,lb,lc,lo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_I_Y,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_I_W,   "we,wa,wb,wc,wo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_I_U,   "le,la,lb,lc,lo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_I_Y,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_I_W,   "we,wa,wb,wc,wo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_I_U,   "le,la,lb,lc,lo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_I_Y,   "Jf,Ji6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_I_W,   "wf,wi6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_I_U,   "lf,li6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_I_Y,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_I_W,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_I_U,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },	
{"sfppushc",   0, INSN_CLASS_I_Y,   "",               MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },
{"sfppushc",   0, INSN_CLASS_I_W,   "wi1",            MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },
{"sfppushc",   0, INSN_CLASS_I_U,   "li1",            MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },	
{"sfppopc",    0, INSN_CLASS_I_Y,   "",               MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfppopc",    0, INSN_CLASS_I_W,   "wi1",            MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfppopc",    0, INSN_CLASS_I_U,   "li1",            MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_I_Y,   "Jg,Jf,Ji1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_I_W,   "wg,wf,wi1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_I_U,   "lg,lf,li1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_I_Y,   "Jh,Jg,Ji2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_I_W,   "wh,wg,wi2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_I_U,   "lh,lg,li2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_I_Y,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_I_W,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_I_U,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"sfpnop",     0, INSN_CLASS_I_W,   "",               MATCH_SFPWNOP,   MASK_SFPWNOP,   sfp_match_opcode, 0 },
{"sfpnop",     0, INSN_CLASS_I_U,   "",               MATCH_SFPWNOP,   MASK_SFPWNOP,   sfp_match_opcode, 0 },
{"ttincrwc",   0, INSN_CLASS_I_Y,   "Jk1,Jk2,Jk3,Jk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttincrwc",   0, INSN_CLASS_I_W,   "wk1,wk2,wk3,wk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttincrwc",   0, INSN_CLASS_I_U,   "lk1,lk2,lk3,lk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttreplay",   0, INSN_CLASS_I_W,   "wl1,wl2,wl3,wl4",MATCH_SFPREPLAY, MASK_SFPREPLAY, sfp_match_opcode, 0 },
{"ttreplay",   0, INSN_CLASS_I_U,   "ll1,ll2,ll3,ll4",MATCH_SFPREPLAY, MASK_SFPREPLAY, sfp_match_opcode, 0 },
{"sfpxor",     0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPXOR,    MASK_SFPXOR,    sfp_match_opcode, 0 },
{"sfpxor",     0, INSN_CLASS_I_U,   "lh,lg",          MATCH_SFPXOR,    MASK_SFPXOR,    sfp_match_opcode, 0 },	
{"sfpcast",    0, INSN_CLASS_I_W,   "we,wc,wi2",      MATCH_SFPCAST,   MASK_SFPCAST,   sfp_match_opcode, 0 },
{"sfpcast",    0, INSN_CLASS_I_U,   "le,lc,li2",      MATCH_SFPCAST,   MASK_SFPCAST,   sfp_match_opcode, 0 },	
{"sfpshft2",   0, INSN_CLASS_I_W,   "we,wc,wi2",      MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, 0 },
{"sfpshft2",   0, INSN_CLASS_I_U,   "le,lc,li2",      MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, 0 },
{"sfpshft2",   0, INSN_CLASS_I_W,   "we,wc,wf,wi2",   MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, INSN_ALIAS },
{"sfpshft2",   0, INSN_CLASS_I_U,   "le,lc,lf,li2",   MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, 0 },
{"sfpconfig",  0, INSN_CLASS_I_W,   "wh,wj,wi7",      MATCH_SFPCONFIG, MASK_SFPCONFIG, sfp_match_opcode, 0 },
{"sfpconfig",  0, INSN_CLASS_I_U,   "lh,lj,li7",      MATCH_SFPCONFIG, MASK_SFPCONFIG, sfp_match_opcode, 0 },
{"sfpswap",    0, INSN_CLASS_I_W,   "wh,wg,wi8",      MATCH_SFPSWAP,   MASK_SFPSWAP,   sfp_match_opcode, 0 },
{"sfpswap",    0, INSN_CLASS_I_U,   "lh,lg,li1",      MATCH_SFPSWAP,   MASK_SFPSWAP,    sfp_match_opcode, 0 },	
{"sfplutfp32", 0, INSN_CLASS_I_W,   "we,wo",          MATCH_SFPLUTFP32,MASK_SFPLUTFP32,sfp_match_opcode, 0 },
{"sfplutfp32", 0, INSN_CLASS_I_U,   "le,lo",          MATCH_SFPLUTFP32,MASK_SFPLUTFP32,sfp_match_opcode, 0 },
{"sfptransp",  0, INSN_CLASS_I_W,   "",               MATCH_SFPTRANSP, MASK_SFPTRANSP, sfp_match_opcode, 0 },
{"sfptransp",  0, INSN_CLASS_I_U,   "",               MATCH_SFPTRANSP, MASK_SFPTRANSP,sfp_match_opcode, 0 },
{"sfploadmacro",0,INSN_CLASS_I_W,  "wd,wq,wm1,wp",   MATCH_SFPLDMACRO,MASK_SFPLDMACRO,sfp_match_opcode, 0 },
{"sfploadmacro",0,INSN_CLASS_I_U,   "ld,lxa3,lm1,lxa2",MATCH_SFPLDMACRO,MASK_SFPLDMACRO,sfp_match_opcode, 0 },
{"sfpstochrnd",0, INSN_CLASS_I_W,   "we,wb,wc,wi1,wr1,wr2", MATCH_SFPSTOCH_RND,  MASK_SFPSTOCH_RND,  sfp_match_opcode, 0 },
{"sfpstochrnd",0, INSN_CLASS_I_U,   "le,lb,lc,li1,lr1,lr2", MATCH_SFPSTOCH_RND,  MASK_SFPSTOCH_RND,  sfp_match_opcode, 0 },
{"sfparecip",  0, INSN_CLASS_I_U,   "lh,lg,lf,li1",   MATCH_SFPARECIP,  MASK_SFPARECIP,  sfp_match_opcode, INSN_ALIAS },
{"sfpgt",      0, INSN_CLASS_I_U,   "lh,lg,lf,li1",   MATCH_SFPGT,      MASK_SFPGT,  sfp_match_opcode, INSN_ALIAS },
{"sfpmul24",   0, INSN_CLASS_I_U,   "le,la,lb,lc,li1", MATCH_SFPMUL24,   MASK_SFPMUL24,  sfp_match_opcode, INSN_ALIAS },
{"sfple",      0, INSN_CLASS_I_U,   "lh,lg,lf,li1",   MATCH_SFPLE,      MASK_SFPLE,  sfp_match_opcode, INSN_ALIAS },


/* DMA Reg Instructions */
{"ttadddmareg",0, INSN_CLASS_I_Y,  "Js4,Js3,Js2,Js1", MATCH_SFPADDDMAREG, MASK_SFPADDDMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttadddmareg",0, INSN_CLASS_I_W,  "ws4,ws3,ws2,ws1", MATCH_SFPADDDMAREG, MASK_SFPADDDMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttadddmareg",0, INSN_CLASS_I_U,  "ls4,ls3,ls2,ls1", MATCH_SFPADDDMAREG, MASK_SFPADDDMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsubdmareg",0, INSN_CLASS_I_Y,  "Js4,Js3,Js2,Js1", MATCH_SFPSUB_DMAREG, MASK_SFPSUB_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsubdmareg",0, INSN_CLASS_I_W,  "ws4,ws3,ws2,ws1", MATCH_SFPSUB_DMAREG, MASK_SFPSUB_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsubdmareg",0, INSN_CLASS_I_U,  "ls4,ls3,ls2,ls1", MATCH_SFPSUB_DMAREG, MASK_SFPSUB_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttmuldmareg",0, INSN_CLASS_I_Y,  "Js4,Js3,Js2,Js1", MATCH_SFPMUL_DMAREG, MASK_SFPMUL_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttmuldmareg",0, INSN_CLASS_I_W,  "ws4,ws3,ws2,ws1", MATCH_SFPMUL_DMAREG, MASK_SFPMUL_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttmuldmareg",0, INSN_CLASS_I_U,  "ls4,ls3,ls2,ls1", MATCH_SFPMUL_DMAREG, MASK_SFPMUL_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsetdmareg",0, INSN_CLASS_I_Y,  "Js6,Js7,Js8,Js9", MATCH_SFPSET_DMAREG, MASK_SFPSET_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsetdmareg",0, INSN_CLASS_I_W,  "ws6,ws7,ws8,ws9", MATCH_SFPSET_DMAREG, MASK_SFPSET_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttsetdmareg",0, INSN_CLASS_I_U,  "ls6,ls7,ls8,ls9", MATCH_SFPSET_DMAREG, MASK_SFPSET_DMAREG, sfp_match_opcode, INSN_ALIAS },	
{"ttshiftdmareg", 0, INSN_CLASS_I_Y, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPSHIFT_DMAREG,  MASK_SFPSHIFT_DMAREG,  sfp_match_opcode, INSN_ALIAS },
{"ttshiftdmareg", 0, INSN_CLASS_I_W, "ws4,ws5,ws3,ws2,ws1", MATCH_SFPSHIFT_DMAREG,  MASK_SFPSHIFT_DMAREG,  sfp_match_opcode, INSN_ALIAS },
{"ttshiftdmareg", 0, INSN_CLASS_I_U, "ls4,ls5,ls3,ls2,ls1", MATCH_SFPSHIFT_DMAREG,  MASK_SFPSHIFT_DMAREG,  sfp_match_opcode, INSN_ALIAS },
{"ttcmpdmareg",   0, INSN_CLASS_I_Y, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPCMP_DMAREG,    MASK_SFPCMP_DMAREG,    sfp_match_opcode, INSN_ALIAS },
{"ttcmpdmareg",   0, INSN_CLASS_I_W, "ws4,ws5,ws3,ws2,ws1", MATCH_SFPCMP_DMAREG,    MASK_SFPCMP_DMAREG,    sfp_match_opcode, INSN_ALIAS },
{"ttcmpdmareg",   0, INSN_CLASS_I_U, "ls4,ls5,ls3,ls2,ls1", MATCH_SFPCMP_DMAREG,    MASK_SFPCMP_DMAREG,    sfp_match_opcode, INSN_ALIAS },
{"ttbitwopdmareg",0, INSN_CLASS_I_Y, "Js4,Js5,Js3,Js2,Js1", MATCH_SFPBITWOP_DMAREG, MASK_SFPBITWOP_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttbitwopdmareg",0, INSN_CLASS_I_W, "ws4,ws5,ws3,ws2,ws1", MATCH_SFPBITWOP_DMAREG, MASK_SFPBITWOP_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttbitwopdmareg",0, INSN_CLASS_I_U, "ls4,ls5,ls3,ls2,ls1", MATCH_SFPBITWOP_DMAREG, MASK_SFPBITWOP_DMAREG, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrxy",    0, INSN_CLASS_I_Y, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRXY, MASK_SFPADDRCRXY, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrxy",    0, INSN_CLASS_I_W, "wsa,wsb,wsc,wsd,wse,wsf", MATCH_SFPADDRCRXY, MASK_SFPADDRCRXY, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrxy",    0, INSN_CLASS_I_U, "lsa,lsb,lsc,lsd,lse,lsf", MATCH_SFPADDRCRXY, MASK_SFPADDRCRXY, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrzw",    0, INSN_CLASS_I_Y, "Jsa,Jsb,Jsc,Jsd,Jse,Jsf", MATCH_SFPADDRCRZW, MASK_SFPADDRCRZW, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrzw",    0, INSN_CLASS_I_W, "wsa,wsb,wsc,wsd,wse,wsf", MATCH_SFPADDRCRZW, MASK_SFPADDRCRZW, sfp_match_opcode, INSN_ALIAS },
{"ttaddrcrzw",    0, INSN_CLASS_I_U, "lsa,lsb,lsc,lsd,lse,lsf", MATCH_SFPADDRCRZW, MASK_SFPADDRCRZW, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s1",    0, INSN_CLASS_I_Y, "Jss,Jsh,Jsj",         MATCH_SFPAPOOL3S1, MASK_SFPAPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s1",    0, INSN_CLASS_I_W, "wss,wsh,wsi,wsj",     MATCH_SFPAPOOL3S1, MASK_SFPAPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s1",    0, INSN_CLASS_I_U, "lss,lsh,lsi,lsj",     MATCH_SFPAPOOL3S1, MASK_SFPAPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s2",    0, INSN_CLASS_I_Y, "Jss,Jsh,Jsj",         MATCH_SFPAPOOL3S2, MASK_SFPAPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s2",    0, INSN_CLASS_I_W, "wss,wsh,wsi,wsj",     MATCH_SFPAPOOL3S2, MASK_SFPAPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttapool3s2",    0, INSN_CLASS_I_U, "lss,lsh,lsi,lsj",     MATCH_SFPAPOOL3S2, MASK_SFPAPOOL3S2, sfp_match_opcode, INSN_ALIAS },	
{"ttatcas",       0, INSN_CLASS_I_Y, "Jsk,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATCAS, MASK_SFPATCAS, sfp_match_opcode, INSN_ALIAS },
{"ttatcas",       0, INSN_CLASS_I_W, "wsk,wsl,ww1,wsn,wso,wsp", MATCH_SFPATCAS, MASK_SFPATCAS, sfp_match_opcode, INSN_ALIAS },
{"ttatcas",       0, INSN_CLASS_I_U, "lsk,lsl,lw1,lsn,lso,lsp", MATCH_SFPATCAS, MASK_SFPATCAS, sfp_match_opcode, INSN_ALIAS },
{"ttatgetm",      0, INSN_CLASS_I_Y, "Jsr",                 MATCH_SFPATGETM, MASK_SFPATGETM, sfp_match_opcode, INSN_ALIAS },
{"ttatgetm",      0, INSN_CLASS_I_W, "wsr",                 MATCH_SFPATGETM, MASK_SFPATGETM, sfp_match_opcode, INSN_ALIAS },
{"ttatgetm",      0, INSN_CLASS_I_U, "lsr",                 MATCH_SFPATGETM, MASK_SFPATGETM, sfp_match_opcode, INSN_ALIAS },	
{"ttatincget",    0, INSN_CLASS_I_Y, "Jsk,Jsm,Jsn,Jso,Jsp", MATCH_SFPATINCGET, MASK_SFPATINCGET, sfp_match_opcode, INSN_ALIAS },
{"ttatincget",    0, INSN_CLASS_I_W, "wsk,wsm,wsn,wso,wsp", MATCH_SFPATINCGET, MASK_SFPATINCGET, sfp_match_opcode, INSN_ALIAS },
{"ttatincget",    0, INSN_CLASS_I_U, "lsk,lsm,lsn,lso,lsp", MATCH_SFPATINCGET, MASK_SFPATINCGET, sfp_match_opcode, INSN_ALIAS },	
{"ttatincgetptr", 0, INSN_CLASS_I_Y, "Jsk,Jsq,Jsl,Jw1,Jsn,Jso,Jsp", MATCH_SFPATINCGETPTR, MASK_SFPATINCGETPTR, sfp_match_opcode, INSN_ALIAS },
{"ttatincgetptr", 0, INSN_CLASS_I_W, "wsk,wsq,wsl,ww1,wsn,wso,wsp", MATCH_SFPATINCGETPTR, MASK_SFPATINCGETPTR, sfp_match_opcode, INSN_ALIAS },
{"ttatincgetptr", 0, INSN_CLASS_I_U, "lsk,lsq,lsl,lw1,lsn,lso,lsp", MATCH_SFPATINCGETPTR, MASK_SFPATINCGETPTR, sfp_match_opcode, INSN_ALIAS },
{"ttatrelm",      0, INSN_CLASS_I_Y, "Jsr",                 MATCH_SFPATRELM, MASK_SFPATRELM, sfp_match_opcode, INSN_ALIAS },
{"ttatrelm",      0, INSN_CLASS_I_W, "wsr",                 MATCH_SFPATRELM, MASK_SFPATRELM, sfp_match_opcode, INSN_ALIAS },
{"ttatrelm",      0, INSN_CLASS_I_U, "lsr",                 MATCH_SFPATRELM, MASK_SFPATRELM, sfp_match_opcode, INSN_ALIAS },
{"ttatswap",      0, INSN_CLASS_I_Y, "Jsk,Jsm,Jso,Jsp",     MATCH_SFPATSWAP, MASK_SFPATSWAP, sfp_match_opcode, INSN_ALIAS },
{"ttatswap",      0, INSN_CLASS_I_W, "wsk,wsm,wso,wsp",     MATCH_SFPATSWAP, MASK_SFPATSWAP, sfp_match_opcode, INSN_ALIAS },
{"ttatswap",      0, INSN_CLASS_I_U, "lsk,lsm,lso,lsp",     MATCH_SFPATSWAP, MASK_SFPATSWAP, sfp_match_opcode, INSN_ALIAS },
{"ttcleardvalid", 0, INSN_CLASS_I_Y, "Jss,Jst",             MATCH_SFPCLEARDVALID, MASK_SFPCLEARDVALID,sfp_match_opcode, INSN_ALIAS },
{"ttcleardvalid", 0, INSN_CLASS_I_W, "wss,wst",             MATCH_SFPCLEARDVALID, MASK_SFPCLEARDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttcleardvalid", 0, INSN_CLASS_I_U, "lss,lst",             MATCH_SFPCLEARDVALID, MASK_SFPCLEARDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttclrexphist",  0, INSN_CLASS_I_Y, "",                    MATCH_SFPCLREXPHIST, MASK_SFPCLREXPHIST,sfp_match_opcode, INSN_ALIAS },
{"ttclrexphist",  0, INSN_CLASS_I_W, "",                    MATCH_SFPCLREXPHIST, MASK_SFPCLREXPHIST,sfp_match_opcode, INSN_ALIAS },
{"ttclrexphist",  0, INSN_CLASS_I_U, "",                    MATCH_SFPCLREXPHIST, MASK_SFPCLREXPHIST,sfp_match_opcode, INSN_ALIAS },	
{"ttconv3s1",     0, INSN_CLASS_I_Y, "Jss,Jsu,Jsv,Jsw",     MATCH_SFPCONV3S1, MASK_SFPCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s1",     0, INSN_CLASS_I_W, "wss,wsu,wsv,wsw",     MATCH_SFPCONV3S1, MASK_SFPCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s1",     0, INSN_CLASS_I_U, "lss,lsu,lxa4,lxa5",   MATCH_SFPCONV3S1, MASK_SFPCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s2",     0, INSN_CLASS_I_Y, "Jss,Jsu,Jsv,Jsw",     MATCH_SFPCONV3S2, MASK_SFPCONV3S2, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s2",     0, INSN_CLASS_I_W, "wss,wsu,wsv,wsw",     MATCH_SFPCONV3S2, MASK_SFPCONV3S2, sfp_match_opcode, INSN_ALIAS },
{"ttconv3s2",     0, INSN_CLASS_I_U, "lss,lsu,lxa4,lxa5",   MATCH_SFPCONV3S2, MASK_SFPCONV3S2, sfp_match_opcode, INSN_ALIAS },
{"ttdmanop",      0, INSN_CLASS_I_Y, "",                      MATCH_SFPDMANOP, MASK_SFPDMANOP,sfp_match_opcode, INSN_ALIAS },
{"ttdmanop",      0, INSN_CLASS_I_W, "",                      MATCH_SFPDMANOP, MASK_SFPDMANOP,sfp_match_opcode, INSN_ALIAS },
{"ttdmanop",      0, INSN_CLASS_I_U, "",                      MATCH_SFPDMANOP, MASK_SFPDMANOP,sfp_match_opcode, INSN_ALIAS },
{"ttdotpv",       0, INSN_CLASS_I_Y, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPDOTPV, MASK_SFPDOTPV, sfp_match_opcode, INSN_ALIAS },
{"ttdotpv",       0, INSN_CLASS_I_W, "wss,wsx,wsy,wsz,wsw",   MATCH_SFPDOTPV, MASK_SFPDOTPV, sfp_match_opcode, INSN_ALIAS },
{"ttdotpv",       0, INSN_CLASS_I_U, "wss,wsx,wsy,lxa0,lxa5", MATCH_SFPDOTPV, MASK_SFPDOTPV, sfp_match_opcode, INSN_ALIAS },
{"ttelwadd",      0, INSN_CLASS_I_Y, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPELWADD, MASK_SFPELWADD, sfp_match_opcode, INSN_ALIAS },
{"ttelwadd",      0, INSN_CLASS_I_W, "wss,wsx,wsy,wsz,wsw",   MATCH_SFPELWADD, MASK_SFPELWADD, sfp_match_opcode, INSN_ALIAS },
{"ttelwadd",      0, INSN_CLASS_I_U, "wss,wsx,wsy,lxa0,lxa5", MATCH_SFPELWADD, MASK_SFPELWADD, sfp_match_opcode, INSN_ALIAS },
{"ttelwmul",      0, INSN_CLASS_I_Y, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPELWMUL, MASK_SFPELWMUL, sfp_match_opcode, INSN_ALIAS },
{"ttelwmul",      0, INSN_CLASS_I_W, "wss,wsx,wsy,wsz,wsw",   MATCH_SFPELWMUL, MASK_SFPELWMUL, sfp_match_opcode, INSN_ALIAS },
{"ttelwmul",      0, INSN_CLASS_I_U, "wss,wsx,wsy,lxa0,lxa5", MATCH_SFPELWMUL, MASK_SFPELWMUL, sfp_match_opcode, INSN_ALIAS },	
{"ttelwsub",      0, INSN_CLASS_I_Y, "Jss,Jt1,Jsz,Jsw",       MATCH_SFPELWSUB, MASK_SFPELWSUB, sfp_match_opcode, INSN_ALIAS },
{"ttelwsub",      0, INSN_CLASS_I_W, "wss,wsx,wsy,wsz,wsw",   MATCH_SFPELWSUB, MASK_SFPELWSUB, sfp_match_opcode, INSN_ALIAS },
{"ttelwsub",      0, INSN_CLASS_I_U, "wss,wsx,wsy,lxa0,lxa5", MATCH_SFPELWSUB, MASK_SFPELWSUB, sfp_match_opcode, INSN_ALIAS },
{"ttflushdma",    0, INSN_CLASS_I_Y, "Jt0",     MATCH_SFPFLUSHDMA, MASK_SFPFLUSHDMA, sfp_match_opcode, INSN_ALIAS },
{"ttflushdma",    0, INSN_CLASS_I_W, "wt0",     MATCH_SFPFLUSHDMA, MASK_SFPFLUSHDMA, sfp_match_opcode, INSN_ALIAS },
{"ttflushdma",    0, INSN_CLASS_I_U, "lt0",     MATCH_SFPFLUSHDMA, MASK_SFPFLUSHDMA, sfp_match_opcode, INSN_ALIAS },
{"ttgapool",      0, INSN_CLASS_I_Y, "Jss,Jt1,Jw8,Jsj",     MATCH_SFPGAPOOL, MASK_SFPGAPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgapool",      0, INSN_CLASS_I_W, "wss,wt1,wsz,wt2,wsj", MATCH_SFPGAPOOL, MASK_SFPGAPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgapool",      0, INSN_CLASS_I_U, "lss,lt1,lsz,lt2,lsj", MATCH_SFPGAPOOL, MASK_SFPGAPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgatesrcrst",  0, INSN_CLASS_I_Y, "Jt3,Jt4",             MATCH_SFPGATESRCRST, MASK_SFPGATESRCRST, sfp_match_opcode, INSN_ALIAS },
{"ttgatesrcrst",  0, INSN_CLASS_I_W, "wt3,wt4",             MATCH_SFPGATESRCRST, MASK_SFPGATESRCRST, sfp_match_opcode, INSN_ALIAS },
{"ttgatesrcrst",  0, INSN_CLASS_I_U, "lt3,lt4",             MATCH_SFPGATESRCRST, MASK_SFPGATESRCRST, sfp_match_opcode, INSN_ALIAS },
{"ttgmpool",      0, INSN_CLASS_I_Y, "Jss,Jt1,Jw8,Jsw",     MATCH_SFPGMPOOL, MASK_SFPGMPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgmpool",      0, INSN_CLASS_I_W, "wss,wt1,wsz,wt2,wsj", MATCH_SFPGMPOOL, MASK_SFPGMPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttgmpool",      0, INSN_CLASS_I_U, "lss,lt1,lsz,lt2,lsj", MATCH_SFPGMPOOL, MASK_SFPGMPOOL, sfp_match_opcode, INSN_ALIAS },
{"ttincadcxy",    0, INSN_CLASS_I_Y, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCXY, MASK_SFPINCADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttincadcxy",    0, INSN_CLASS_I_W, "wsa,wsb,wsc,wsd,wse", MATCH_SFPINCADCXY, MASK_SFPINCADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttincadcxy",    0, INSN_CLASS_I_U, "lsa,lsb,lsc,lsd,lse", MATCH_SFPINCADCXY, MASK_SFPINCADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttincadczw",    0, INSN_CLASS_I_Y, "Jsa,Jsb,Jsc,Jsd,Jse", MATCH_SFPINCADCZW, MASK_SFPINCADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttincadczw",    0, INSN_CLASS_I_W, "wsa,wsb,wsc,wsd,wse", MATCH_SFPINCADCZW, MASK_SFPINCADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttincadczw",    0, INSN_CLASS_I_U, "lsa,lsb,lsc,lsd,lse", MATCH_SFPINCADCZW, MASK_SFPINCADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttloadind",     0, INSN_CLASS_I_Y, "Jt9,Jta,Jtb,Jso,Jsp", MATCH_SFPLOADIND, MASK_SFPLOADIND, sfp_match_opcode, INSN_ALIAS },
{"ttloadind",     0, INSN_CLASS_I_W, "wt9,wta,wtb,wso,wsp", MATCH_SFPLOADIND, MASK_SFPLOADIND, sfp_match_opcode, INSN_ALIAS },
{"ttloadind",     0, INSN_CLASS_I_U, "lt9,lta,ltb,lso,lsp", MATCH_SFPLOADIND, MASK_SFPLOADIND, sfp_match_opcode, INSN_ALIAS },
{"ttloadreg",     0, INSN_CLASS_I_Y, "Jtc,Jtd",             MATCH_SFPLOADREG, MASK_SFPLOADREG, sfp_match_opcode, INSN_ALIAS },
{"ttloadreg",     0, INSN_CLASS_I_W, "wtc,wtd",             MATCH_SFPLOADREG, MASK_SFPLOADREG, sfp_match_opcode, INSN_ALIAS },
{"ttloadreg",     0, INSN_CLASS_I_U, "ltc,ltd",             MATCH_SFPLOADREG, MASK_SFPLOADREG, sfp_match_opcode, INSN_ALIAS },
{"ttmfconv3s1",   0, INSN_CLASS_I_W, "wss,wte,wsv,wsw",     MATCH_SFPMFCONV3S1, MASK_SFPMFCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmfconv3s1",   0, INSN_CLASS_I_U, "wss,wte,lxa4,lxa5",   MATCH_SFPMFCONV3S1, MASK_SFPMFCONV3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmop",         0, INSN_CLASS_I_Y, "Jtf,Jtg,Jth",         MATCH_SFPMOP, MASK_SFPMOP, sfp_match_opcode, INSN_ALIAS },
{"ttmop",         0, INSN_CLASS_I_W, "wtf,wtg,wth",         MATCH_SFPMOP, MASK_SFPMOP, sfp_match_opcode, INSN_ALIAS },
{"ttmop",         0, INSN_CLASS_I_U, "ltf,ltg,lth",         MATCH_SFPMOP, MASK_SFPMOP, sfp_match_opcode, INSN_ALIAS },
{"ttmopcfg",      0, INSN_CLASS_I_Y, "Jti",                 MATCH_SFPMOP_CFG, MASK_SFPMOP_CFG, sfp_match_opcode, INSN_ALIAS },
{"ttmopcfg",      0, INSN_CLASS_I_W, "wti",                 MATCH_SFPMOP_CFG, MASK_SFPMOP_CFG, sfp_match_opcode, INSN_ALIAS },
{"ttmopcfg",      0, INSN_CLASS_I_U, "lti",                 MATCH_SFPMOP_CFG, MASK_SFPMOP_CFG, sfp_match_opcode, INSN_ALIAS },
{"ttmova2d",      0, INSN_CLASS_I_Y, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVA2D, MASK_SFPMOVA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmova2d",      0, INSN_CLASS_I_W, "wtj,wtk,wsv,wtl,wtm",   MATCH_SFPMOVA2D, MASK_SFPMOVA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmova2d",      0, INSN_CLASS_I_U, "ltj,ltk,lxa4,lxa6,ltm", MATCH_SFPMOVA2D, MASK_SFPMOVA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2a",      0, INSN_CLASS_I_Y, "Jtn,Jsv,Jtl,Jto",       MATCH_SFPMOVB2A, MASK_SFPMOVB2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2a",      0, INSN_CLASS_I_W, "wtn,wsv,wtl,wto",       MATCH_SFPMOVB2A, MASK_SFPMOVB2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2a",      0, INSN_CLASS_I_U, "ltn,lxa7,lxa6,wto",     MATCH_SFPMOVB2A, MASK_SFPMOVB2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2d",      0, INSN_CLASS_I_Y, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVB2D, MASK_SFPMOVB2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2d",      0, INSN_CLASS_I_W, "wtj,wtk,wsv,wtl,wtm",   MATCH_SFPMOVB2D, MASK_SFPMOVB2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovb2d",      0, INSN_CLASS_I_U, "ltj,ltk,lxa4,ltl,lxaa", MATCH_SFPMOVB2D, MASK_SFPMOVB2D, sfp_match_opcode, INSN_ALIAS },	
{"ttmovd2a",      0, INSN_CLASS_I_Y, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVD2A, MASK_SFPMOVD2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2a",      0, INSN_CLASS_I_W, "wtj,wtk,wsv,wtl,wtm",   MATCH_SFPMOVD2A, MASK_SFPMOVD2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2a",      0, INSN_CLASS_I_U, "ltj,ltk,lxa4,lxa6,ltm", MATCH_SFPMOVD2A, MASK_SFPMOVD2A, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2b",      0, INSN_CLASS_I_Y, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVD2B, MASK_SFPMOVD2B, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2b",      0, INSN_CLASS_I_W, "wtj,wtk,wsv,wtl,wtm",   MATCH_SFPMOVD2B, MASK_SFPMOVD2B, sfp_match_opcode, INSN_ALIAS },
{"ttmovd2b",      0, INSN_CLASS_I_U, "ltj,ltk,lxa4,lxa6,ltm", MATCH_SFPMOVD2B, MASK_SFPMOVD2B, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbga2d",   0, INSN_CLASS_I_Y, "Jw3,Jsz,Jw4,Jw5",       MATCH_SFPMOVDBGA2D, MASK_SFPMOVDBGA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbga2d",   0, INSN_CLASS_I_W, "wtj,wtk,wsv,wtl,wtm",   MATCH_SFPMOVDBGA2D, MASK_SFPMOVDBGA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbga2d",   0, INSN_CLASS_I_U, "ltj,ltk,lxa4,lxa6,ltm", MATCH_SFPMOVDBGA2D, MASK_SFPMOVDBGA2D, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s1",    0, INSN_CLASS_I_Y, "Jss,Jsh,Jsj",     MATCH_SFPMPOOL3S1, MASK_SFPMPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s1",    0, INSN_CLASS_I_W, "wss,wsh,wsi,wsj", MATCH_SFPMPOOL3S1, MASK_SFPMPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s1",    0, INSN_CLASS_I_U, "lss,lsh,lsi,lsj", MATCH_SFPMPOOL3S1, MASK_SFPMPOOL3S1, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s2",    0, INSN_CLASS_I_Y, "Jss,Jsh,Jsw",     MATCH_SFPMPOOL3S2, MASK_SFPMPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s2",    0, INSN_CLASS_I_W, "wss,wsh,wsi,wsj", MATCH_SFPMPOOL3S2, MASK_SFPMPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttmpool3s2",    0, INSN_CLASS_I_U, "lss,lsh,lsi,lsj", MATCH_SFPMPOOL3S2, MASK_SFPMPOOL3S2, sfp_match_opcode, INSN_ALIAS },
{"ttmvmul",       0, INSN_CLASS_I_Y, "Jss,Jt1,Jsz,Jsw",     MATCH_SFPMVMUL, MASK_SFPMVMUL, sfp_match_opcode, INSN_ALIAS },
{"ttmvmul",       0, INSN_CLASS_I_W, "wss,wt1,wsz,wsw",     MATCH_SFPMVMUL, MASK_SFPMVMUL, sfp_match_opcode, INSN_ALIAS },
{"ttmvmul",       0, INSN_CLASS_I_U, "lss,lt1,lxa0,lxa5",   MATCH_SFPMVMUL, MASK_SFPMVMUL, sfp_match_opcode, INSN_ALIAS },	
{"ttpacr",        0, INSN_CLASS_I_Y, "Jtp,Jtq,Jty,Jtr,Jts,Jtt,Jtu", MATCH_SFP_PACR, MASK_SFP_PACR, sfp_match_opcode, INSN_ALIAS },
{"ttpacr",        0, INSN_CLASS_I_W, "wtp,wtq,wty,wtr,wts,wtt,wtu", MATCH_SFP_PACR, MASK_SFP_PACR, sfp_match_opcode, INSN_ALIAS },
{"ttpacr",        0, INSN_CLASS_I_U, "lxab,lxac,lxad,lxae,lxaf,lxag,lxah,lxai,lxaj,lxak,lxal,lxam", MATCH_SFP_PACR, MASK_SFP_PACR, sfp_match_opcode, INSN_ALIAS },
{"ttpacrsetreg",  0, INSN_CLASS_I_W, "wtv,wtw,wtx,wty,wtz,wu0,wtu", MATCH_SFP_PACR_SETREG, MASK_SFP_PACR_SETREG, sfp_match_opcode, INSN_ALIAS },
{"ttpacrsetreg",  0, INSN_CLASS_I_U, "lxan,lxao,lxap,lxaq,lxar,lxas,lxal,lxam", MATCH_SFP_PACR_SETREG, MASK_SFP_PACR_SETREG, sfp_match_opcode, INSN_ALIAS },
{"ttrareb",       0, INSN_CLASS_I_Y, "",                MATCH_SFP_RAREB, MASK_SFP_RAREB, sfp_match_opcode, INSN_ALIAS },
{"ttrareb",       0, INSN_CLASS_I_W, "",                MATCH_SFP_RAREB, MASK_SFP_RAREB, sfp_match_opcode, INSN_ALIAS },
{"ttrareb",       0, INSN_CLASS_I_U, "",                MATCH_SFP_RAREB, MASK_SFP_RAREB, sfp_match_opcode, INSN_ALIAS },
{"ttrdcfg",       0, INSN_CLASS_I_Y, "Ju1,Ju2",         MATCH_SFP_RDCFG, MASK_SFP_RDCFG,sfp_match_opcode, INSN_ALIAS },
{"ttrdcfg",       0, INSN_CLASS_I_W, "wu1,wu2",         MATCH_SFP_RDCFG, MASK_SFP_RDCFG,sfp_match_opcode, INSN_ALIAS },
{"ttrdcfg",       0, INSN_CLASS_I_U, "lu1,lu2",         MATCH_SFP_RDCFG, MASK_SFP_RDCFG,sfp_match_opcode, INSN_ALIAS },
{"ttreg2flop",    0, INSN_CLASS_I_Y, "Jt9,Ju3,Ju4,Ju5,Ju6,Ju7", MATCH_SFP_REG2FLOP, MASK_SFP_REG2FLOP, sfp_match_opcode, INSN_ALIAS },
{"ttreg2flop",    0, INSN_CLASS_I_W, "wt9,wu3,wu4,wu5,wu6,wu7", MATCH_SFP_REG2FLOP, MASK_SFP_REG2FLOP, sfp_match_opcode, INSN_ALIAS },
{"ttreg2flop",    0, INSN_CLASS_I_U, "lt9,lu3,lu4,lu5,lu6,lu7", MATCH_SFP_REG2FLOP, MASK_SFP_REG2FLOP, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib0",     0, INSN_CLASS_I_W, "wuc,wud,wue",     MATCH_SFP_RMWCIB0, MASK_SFP_RMWCIB0, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib0",     0, INSN_CLASS_I_U, "luc,lud,lue",     MATCH_SFP_RMWCIB0, MASK_SFP_RMWCIB0, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib1",     0, INSN_CLASS_I_W, "wuc,wud,wue",     MATCH_SFP_RMWCIB1, MASK_SFP_RMWCIB1, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib1",     0, INSN_CLASS_I_U, "luc,lud,lue",     MATCH_SFP_RMWCIB1, MASK_SFP_RMWCIB1, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib2",     0, INSN_CLASS_I_W, "wuc,wud,wue",     MATCH_SFP_RMWCIB2, MASK_SFP_RMWCIB2, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib2",     0, INSN_CLASS_I_U, "luc,lud,lue",     MATCH_SFP_RMWCIB2, MASK_SFP_RMWCIB2, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib3",     0, INSN_CLASS_I_W, "wuc,wud,wue",     MATCH_SFP_RMWCIB3, MASK_SFP_RMWCIB3, sfp_match_opcode, INSN_ALIAS },
{"ttrmwcib3",     0, INSN_CLASS_I_U, "luc,lud,lue",     MATCH_SFP_RMWCIB3, MASK_SFP_RMWCIB3, sfp_match_opcode, INSN_ALIAS },
{"ttrstdma",      0, INSN_CLASS_I_Y, "",                MATCH_SFP_RSTDMA, MASK_SFP_RSTDMA,sfp_match_opcode, INSN_ALIAS },
{"ttrstdma",      0, INSN_CLASS_I_W, "",                MATCH_SFP_RSTDMA, MASK_SFP_RSTDMA,sfp_match_opcode, INSN_ALIAS },
{"ttrstdma",      0, INSN_CLASS_I_U, "",                MATCH_SFP_RSTDMA, MASK_SFP_RSTDMA,sfp_match_opcode, INSN_ALIAS },

{"ttsemget",      0, INSN_CLASS_I_Y, "Juf",             MATCH_SFP_SEMGET, MASK_SFP_SEMGET,sfp_match_opcode, INSN_ALIAS },
{"ttsemget",      0, INSN_CLASS_I_W, "wuf",             MATCH_SFP_SEMGET, MASK_SFP_SEMGET,sfp_match_opcode, INSN_ALIAS },
{"ttsemget",      0, INSN_CLASS_I_U, "luf",             MATCH_SFP_SEMGET, MASK_SFP_SEMGET,sfp_match_opcode, INSN_ALIAS },
{"ttseminit",     0, INSN_CLASS_I_Y, "Jug,Juh,Jui",     MATCH_SFP_SEMINIT, MASK_SFP_SEMINIT, sfp_match_opcode, INSN_ALIAS },
{"ttseminit",     0, INSN_CLASS_I_W, "wug,wuh,wui",     MATCH_SFP_SEMINIT, MASK_SFP_SEMINIT, sfp_match_opcode, INSN_ALIAS },
{"ttseminit",     0, INSN_CLASS_I_U, "lug,luh,lui",     MATCH_SFP_SEMINIT, MASK_SFP_SEMINIT, sfp_match_opcode, INSN_ALIAS },
{"ttsempost",     0, INSN_CLASS_I_Y, "Juf",             MATCH_SFP_SEMPOST, MASK_SFP_SEMPOST, sfp_match_opcode, INSN_ALIAS },
{"ttsempost",     0, INSN_CLASS_I_W, "wuf",             MATCH_SFP_SEMPOST, MASK_SFP_SEMPOST, sfp_match_opcode, INSN_ALIAS },
{"ttsempost",     0, INSN_CLASS_I_U, "luf",             MATCH_SFP_SEMPOST, MASK_SFP_SEMPOST, sfp_match_opcode, INSN_ALIAS },
{"ttsemwait",     0, INSN_CLASS_I_Y, "Jw6,Jw7,Jul",     MATCH_SFP_SEMWAIT, MASK_SFP_SEMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttsemwait",     0, INSN_CLASS_I_W, "wuj,wuk,wul",     MATCH_SFP_SEMWAIT, MASK_SFP_SEMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttsemwait",     0, INSN_CLASS_I_U, "luj,luk,lul",     MATCH_SFP_SEMWAIT, MASK_SFP_SEMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttsetadc",      0, INSN_CLASS_I_Y, "Jsa,Jum,Jun,Juo", MATCH_SFP_SETADC, MASK_SFP_SETADC, sfp_match_opcode, INSN_ALIAS },
{"ttsetadc",      0, INSN_CLASS_I_W, "wsa,wum,wun,wuo", MATCH_SFP_SETADC, MASK_SFP_SETADC, sfp_match_opcode, INSN_ALIAS },
{"ttsetadc",      0, INSN_CLASS_I_U, "lsa,lum,lun,luo", MATCH_SFP_SETADC, MASK_SFP_SETADC, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxx",    0, INSN_CLASS_I_Y, "Jsa,Jup,Juq",     MATCH_SFP_SETADCXX, MASK_SFP_SETADCXX, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxx",    0, INSN_CLASS_I_W, "wsa,wup,wuq",     MATCH_SFP_SETADCXX, MASK_SFP_SETADCXX, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxx",    0, INSN_CLASS_I_U, "lsa,lup,luq",     MATCH_SFP_SETADCXX, MASK_SFP_SETADCXX, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxy",    0, INSN_CLASS_I_Y, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCXY, MASK_SFP_SETADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxy",    0, INSN_CLASS_I_W, "wsa,wsb,wsc,wsd,wse,wur", MATCH_SFP_SETADCXY, MASK_SFP_SETADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttsetadcxy",    0, INSN_CLASS_I_U, "lsa,lsb,lsc,lsd,lse,lur", MATCH_SFP_SETADCXY, MASK_SFP_SETADCXY, sfp_match_opcode, INSN_ALIAS },
{"ttsetadczw",    0, INSN_CLASS_I_Y, "Jsa,Jsb,Jsc,Jsd,Jse,Jur", MATCH_SFP_SETADCZW, MASK_SFP_SETADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttsetadczw",    0, INSN_CLASS_I_W, "wsa,wsb,wsc,wsd,wse,wur", MATCH_SFP_SETADCZW, MASK_SFP_SETADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttsetadczw",    0, INSN_CLASS_I_U, "lsa,lsb,lsc,lsd,lse,lur", MATCH_SFP_SETADCZW, MASK_SFP_SETADCZW, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh",   0, INSN_CLASS_I_Y, "Jus,Jut",         MATCH_SFP_SETASHRMH, MASK_SFP_SETASHRMH, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh",   0, INSN_CLASS_I_W, "wus,wut",         MATCH_SFP_SETASHRMH, MASK_SFP_SETASHRMH, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh",   0, INSN_CLASS_I_U, "lus,lut",         MATCH_SFP_SETASHRMH, MASK_SFP_SETASHRMH, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh0",  0, INSN_CLASS_I_Y, "Jus,Jut",         MATCH_SFP_SETASHRMH0, MASK_SFP_SETASHRMH0, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh0",  0, INSN_CLASS_I_W, "wus,wut",         MATCH_SFP_SETASHRMH0, MASK_SFP_SETASHRMH0, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh0",  0, INSN_CLASS_I_U, "lus,lut",         MATCH_SFP_SETASHRMH0, MASK_SFP_SETASHRMH0, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh1",  0, INSN_CLASS_I_Y, "Jus,Jut",         MATCH_SFP_SETASHRMH1, MASK_SFP_SETASHRMH1, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh1",  0, INSN_CLASS_I_W, "wus,wut",         MATCH_SFP_SETASHRMH1, MASK_SFP_SETASHRMH1, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmh1",  0, INSN_CLASS_I_U, "lus,lut",         MATCH_SFP_SETASHRMH1, MASK_SFP_SETASHRMH1, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmv",   0, INSN_CLASS_I_Y, "Juu",             MATCH_SFP_SETASHRMV, MASK_SFP_SETASHRMV, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmv",   0, INSN_CLASS_I_W, "wuu",             MATCH_SFP_SETASHRMV, MASK_SFP_SETASHRMV, sfp_match_opcode, INSN_ALIAS },
{"ttsetashrmv",   0, INSN_CLASS_I_U, "luu",             MATCH_SFP_SETASHRMV, MASK_SFP_SETASHRMV, sfp_match_opcode, INSN_ALIAS },
{"ttsetc16",      0, INSN_CLASS_I_Y, "Juv,Juw",         MATCH_SFP_SETC16, MASK_SFP_SETC16, sfp_match_opcode, INSN_ALIAS },
{"ttsetc16",      0, INSN_CLASS_I_W, "wuv,wuw",         MATCH_SFP_SETC16, MASK_SFP_SETC16, sfp_match_opcode, INSN_ALIAS },
{"ttsetc16",      0, INSN_CLASS_I_U, "luv,luw",         MATCH_SFP_SETC16, MASK_SFP_SETC16, sfp_match_opcode, INSN_ALIAS },
{"ttsetdvalid",   0, INSN_CLASS_I_Y, "Juw",             MATCH_SFP_SETDVALID, MASK_SFP_SETDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttsetdvalid",   0, INSN_CLASS_I_W, "wuw",             MATCH_SFP_SETDVALID, MASK_SFP_SETDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttsetdvalid",   0, INSN_CLASS_I_U, "luw",             MATCH_SFP_SETDVALID, MASK_SFP_SETDVALID, sfp_match_opcode, INSN_ALIAS },
{"ttsetibrwc",    0, INSN_CLASS_I_W, "wt5,wuy,wuz",     MATCH_SFP_SETIBRWC, MASK_SFP_SETIBRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetibrwc",    0, INSN_CLASS_I_U, "lt5,luy,luz",     MATCH_SFP_SETIBRWC, MASK_SFP_SETIBRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetpkedgof",  0, INSN_CLASS_I_Y, "Jv0,Jv1,Jv2,Jw2", MATCH_SFP_SETPKEDGOF, MASK_SFP_SETPKEDGOF, sfp_match_opcode, INSN_ALIAS },
{"ttsetpkedgof",  0, INSN_CLASS_I_W, "wv0,wv1,wv2,ww2", MATCH_SFP_SETPKEDGOF, MASK_SFP_SETPKEDGOF, sfp_match_opcode, INSN_ALIAS },
{"ttsetpkedgof",  0, INSN_CLASS_I_U, "lv0,lv1,lv2,lw2", MATCH_SFP_SETPKEDGOF, MASK_SFP_SETPKEDGOF, sfp_match_opcode, INSN_ALIAS },
{"ttsetrwc",      0, INSN_CLASS_I_Y, "Jv3,Jt5,Jt6,Jt7,Jt8,Jur", MATCH_SFP_SETRWC, MASK_SFP_SETRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetrwc",      0, INSN_CLASS_I_W, "wv3,wt5,wt6,wt7,wt8,wur", MATCH_SFP_SETRWC, MASK_SFP_SETRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsetrwc",      0, INSN_CLASS_I_U, "lv3,lt5,lt6,lt7,lt8,lur", MATCH_SFP_SETRWC, MASK_SFP_SETRWC, sfp_match_opcode, INSN_ALIAS },
{"ttsfploadmacro",0, INSN_CLASS_I_W, "wv4,wv5,wv6,wv7", MATCH_SFP_SFPLOADMACRO, MASK_SFP_SFPLOADMACRO, sfp_match_opcode, INSN_ALIAS },
{"ttsfploadmacro",0, INSN_CLASS_I_U, "lv4,lv5,ls2,ls1", MATCH_SFP_SFPLOADMACRO, MASK_SFP_SFPLOADMACRO, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxa",     0, INSN_CLASS_I_Y, "Jv8,Jv9",         MATCH_SFPSHIFTXA, MASK_SFPSHIFTXA, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxa",     0, INSN_CLASS_I_W, "wv8,wv9",         MATCH_SFPSHIFTXA, MASK_SFPSHIFTXA, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxa",     0, INSN_CLASS_I_U, "lv8,lv9",         MATCH_SFPSHIFTXA, MASK_SFPSHIFTXA, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxb",     0, INSN_CLASS_I_W, "wtp,wva,wvb",     MATCH_SFPSHIFTXB, MASK_SFPSHIFTXB, sfp_match_opcode, INSN_ALIAS },
{"ttshiftxb",     0, INSN_CLASS_I_U, "lxat,lxau,lvb",   MATCH_SFPSHIFTXB, MASK_SFPSHIFTXB, sfp_match_opcode, INSN_ALIAS },
{"ttstallwait",   0, INSN_CLASS_I_Y, "Jw6,Jsg",         MATCH_SFPSTALLWAIT, MASK_SFPSTALLWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstallwait",   0, INSN_CLASS_I_W, "wuj,wvc",         MATCH_SFPSTALLWAIT, MASK_SFPSTALLWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstallwait",   0, INSN_CLASS_I_U, "luj,lvc",         MATCH_SFPSTALLWAIT, MASK_SFPSTALLWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstoreind",    0, INSN_CLASS_I_Y, "Jsk,Jvd,Jve,Jvf,Jtb,Jso,Jsp", MATCH_SFPSTOREIND, MASK_SFPSTOREIND, sfp_match_opcode, INSN_ALIAS },
{"ttstoreind",    0, INSN_CLASS_I_W, "wsk,wvd,wve,wvf,wtb,wso,wsp", MATCH_SFPSTOREIND, MASK_SFPSTOREIND, sfp_match_opcode, INSN_ALIAS },
{"ttstoreind",    0, INSN_CLASS_I_U, "lsk,lvd,lve,lvf,ltb,lso,lsp", MATCH_SFPSTOREIND, MASK_SFPSTOREIND, sfp_match_opcode, INSN_ALIAS },
{"ttstorereg",    0, INSN_CLASS_I_Y, "Jtc,Jtd",         MATCH_SFPSTOREREG, MASK_SFPSTOREREG, sfp_match_opcode, INSN_ALIAS },
{"ttstorereg",    0, INSN_CLASS_I_W, "wtc,wtd",         MATCH_SFPSTOREREG, MASK_SFPSTOREREG, sfp_match_opcode, INSN_ALIAS },
{"ttstorereg",    0, INSN_CLASS_I_U, "ltc,ltd",         MATCH_SFPSTOREREG, MASK_SFPSTOREREG, sfp_match_opcode, INSN_ALIAS },
{"tttbufcmd",     0, INSN_CLASS_I_W, "",                MATCH_SFPTBUFCMD, MASK_SFPTBUFCMD, sfp_match_opcode, INSN_ALIAS },
{"tttbufcmd",     0, INSN_CLASS_I_U, "",                MATCH_SFPTBUFCMD, MASK_SFPTBUFCMD, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrca",   0, INSN_CLASS_I_Y, "",                MATCH_SFPTRNSPSRCA, MASK_SFPTRNSPSRCA, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrca",   0, INSN_CLASS_I_W, "",                MATCH_SFPTRNSPSRCA, MASK_SFPTRNSPSRCA, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrca",   0, INSN_CLASS_I_U, "",                MATCH_SFPTRNSPSRCA, MASK_SFPTRNSPSRCA, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrcb",   0, INSN_CLASS_I_W, "",                MATCH_SFPTRNSPSRCB, MASK_SFPTRNSPSRCB, sfp_match_opcode, INSN_ALIAS },
{"tttrnspsrcb",   0, INSN_CLASS_I_U, "",                MATCH_SFPTRNSPSRCB, MASK_SFPTRNSPSRCB, sfp_match_opcode, INSN_ALIAS },
{"ttunpacr",      0, INSN_CLASS_I_Y, "Jvg,Jvh,Jvi,Jvj,Jvk,Jtr,Jvl,Jvm,Jvn,Jvo,Jvp,Jvq,Jt4", MATCH_SFPUNPACR, MASK_SFPUNPACR, sfp_match_opcode, INSN_ALIAS },
{"ttunpacr",      0, INSN_CLASS_I_W, "wvg,wvh,wvi,wvj,wvk,wtr,wvl,wvm,wvn,wvo,wvp,wvq,wt4", MATCH_SFPUNPACR, MASK_SFPUNPACR, sfp_match_opcode, INSN_ALIAS },
{"ttunpacr",      0, INSN_CLASS_I_U, "lxba,lxbb,lxbc,lxbd,lxbe,lxbf,lxbg,lxbh,lxbi,lxbj,lxbk,lxbl,lxam", MATCH_SFPUNPACR, MASK_SFPUNPACR, sfp_match_opcode, INSN_ALIAS },
{"ttunpacrnop",   0, INSN_CLASS_I_Y, "Jvg,Jvr",         MATCH_SFPUNPACR_NOP, MASK_SFPUNPACR_NOP, sfp_match_opcode, INSN_ALIAS },
{"ttunpacrnop",   0, INSN_CLASS_I_W, "wvg,wvr",         MATCH_SFPUNPACR_NOP, MASK_SFPUNPACR_NOP, sfp_match_opcode, INSN_ALIAS },
{"ttunpacrnop",   0, INSN_CLASS_I_U, "lxbm,lxbn,lxbo,lxbp,lxbq,lxbr,lxbs,lxbt,lxbu", MATCH_SFPUNPACR_NOP, MASK_SFPUNPACR_NOP, sfp_match_opcode, INSN_ALIAS },
{"ttwrcfg",       0, INSN_CLASS_I_Y, "Ju1,Jvs,Jvt",     MATCH_SFPWRCFG, MASK_SFPWRCFG, sfp_match_opcode, INSN_ALIAS },
{"ttwrcfg",       0, INSN_CLASS_I_W, "wu1,wvs,wvt",     MATCH_SFPWRCFG, MASK_SFPWRCFG, sfp_match_opcode, INSN_ALIAS },
{"ttwrcfg",       0, INSN_CLASS_I_U, "lu1,lvs,lvt",     MATCH_SFPWRCFG, MASK_SFPWRCFG, sfp_match_opcode, INSN_ALIAS },
{"ttxmov",        0, INSN_CLASS_I_Y, "Jvu,Jvv",         MATCH_SFPXMOV, MASK_SFPXMOV, sfp_match_opcode, INSN_ALIAS },
{"ttxmov",        0, INSN_CLASS_I_W, "wvu,wvv",         MATCH_SFPXMOV, MASK_SFPXMOV, sfp_match_opcode, INSN_ALIAS },
{"ttxmov",        0, INSN_CLASS_I_U, "lvu,lvv",         MATCH_SFPXMOV, MASK_SFPXMOV, sfp_match_opcode, INSN_ALIAS },
{"ttzeroacc",     0, INSN_CLASS_I_Y, "Jvw,Jsz,Jsw",     MATCH_SFPZEROACC, MASK_SFPZEROACC, sfp_match_opcode, INSN_ALIAS },
{"ttzeroacc",     0, INSN_CLASS_I_W, "wvw,wsz,wsw",     MATCH_SFPZEROACC, MASK_SFPZEROACC, sfp_match_opcode, INSN_ALIAS },
{"ttzeroacc",     0, INSN_CLASS_I_U, "lvw,lxc0,lxc1,lxc2,lxc3", MATCH_SFPZEROACC, MASK_SFPZEROACC, sfp_match_opcode, INSN_ALIAS },
{"ttzerosrc",     0, INSN_CLASS_I_Y, "Jvx,Jvy,Jvz,Jw0", MATCH_SFPZEROSRC, MASK_SFPZEROSRC, sfp_match_opcode, INSN_ALIAS },
{"ttzerosrc",     0, INSN_CLASS_I_W, "wvx,wvy,wvz,ww0", MATCH_SFPZEROSRC, MASK_SFPZEROSRC, sfp_match_opcode, INSN_ALIAS },
{"ttzerosrc",     0, INSN_CLASS_I_U, "lvx,lvy,lvz,lw0", MATCH_SFPZEROSRC, MASK_SFPZEROSRC, sfp_match_opcode, INSN_ALIAS },
{"ttcfgshiftmask",0, INSN_CLASS_I_U, "lxav,lxaw,lxax,lxay,lxaz,lxbv", MATCH_SFPCFGSHIFTMASK, MASK_SFPCFGSHIFTMASK, sfp_match_opcode, INSN_ALIAS },
{"ttmovdbgb2d",   0, INSN_CLASS_I_U, "ltj,ltk,lxa4,lxc4,lxaa", MATCH_SFPMOVDBGB2D, MASK_SFPMOVDBGB2D, sfp_match_opcode, INSN_ALIAS },
{"ttresourcedecl",0, INSN_CLASS_I_U, "lxbw,lxbx,lxby",        MATCH_SFPRESOURCEDECL, MASK_SFPRESOURCEDECL, sfp_match_opcode, INSN_ALIAS },
{"ttstreamwait",  0, INSN_CLASS_I_U, "luj,lxbz,lxb0,lxb1",    MATCH_SFPSTREAMWAIT, MASK_SFPSTREAMWAIT, sfp_match_opcode, INSN_ALIAS },
{"ttstreamwrcfg", 0, INSN_CLASS_I_U, "lxb2,lxb3,lxb4",        MATCH_SFPSTREAMWRCFG, MASK_SFPSTREAMWRCFG, sfp_match_opcode, INSN_ALIAS },

#endif  // RISCV_OPC_SFPU_INSNS_H
