
/* SFPU Grayskull Instructions.  */
{"sfpload",    0, INSN_CLASS_I_Y,   "Jd1,Jn,Jm1",     MATCH_SFPLOAD,   MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfpload",    0, INSN_CLASS_I_W,   "wd1,wq,wm1,wp",  MATCH_SFPLOAD,   MASK_SFPLOAD,   sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_I_Y,   "Jd1,Jn,Jm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },
{"sfploadi",   0, INSN_CLASS_I_W,   "wd1,wn,wm1",     MATCH_SFPLOADI,  MASK_SFPLOADI,  sfp_match_opcode, INSN_ALIAS },
{"sfpstore",   0, INSN_CLASS_I_Y,   "Jn,Jd2,Jm2",     MATCH_SFPSTORE,  MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },
{"sfpstore",   0, INSN_CLASS_I_W,   "wq,wd2,wm1,wp",  MATCH_SFPSTORE,  MASK_SFPSTORE,  sfp_match_opcode, INSN_ALIAS },
{"sfplut",     0, INSN_CLASS_I_Y,   "Jd1,Jm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },
{"sfplut",     0, INSN_CLASS_I_W,   "wd1,wm3",        MATCH_SFPLUT,    MASK_SFPLUT,    sfp_match_opcode, INSN_ALIAS },
{"sfpmuli",    0, INSN_CLASS_I_Y,   "Jh,Jj,Ji3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },
{"sfpmuli",    0, INSN_CLASS_I_W,   "wh,wj,wi3",      MATCH_SFPMULI,   MASK_SFPMULI,   sfp_match_opcode, INSN_ALIAS },
{"sfpaddi",    0, INSN_CLASS_I_Y,   "Jh,Jj,Ji3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },
{"sfpaddi",    0, INSN_CLASS_I_W,   "wh,wj,wi3",      MATCH_SFPADDI,   MASK_SFPADDI,   sfp_match_opcode, INSN_ALIAS },
{"sfpdivp2",   0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },
{"sfpdivp2",   0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPDIVP2,  MASK_SFPDIVP2,  sfp_match_opcode, INSN_ALIAS },
{"sfpexexp",   0, INSN_CLASS_I_Y,   "Jh,Jg,Ji4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },
{"sfpexexp",   0, INSN_CLASS_I_W,   "wh,wg,wi4",      MATCH_SFPEXEXP,  MASK_SFPEXEXP,  sfp_match_opcode, INSN_ALIAS },
{"sfpexman",   0, INSN_CLASS_I_Y,   "Jh,Jg,Ji2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },
{"sfpexman",   0, INSN_CLASS_I_W,   "wh,wg,wi2",      MATCH_SFPEXMAN,  MASK_SFPEXMAN,  sfp_match_opcode, INSN_ALIAS },
{"sfpiadd",    0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },
{"sfpiadd",    0, INSN_CLASS_I_W,   "wh,wg,wf,wi5",   MATCH_SFPIADD,   MASK_SFPIADD,   sfp_match_opcode, INSN_ALIAS },
{"sfpshft",    0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },
{"sfpshft",    0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSHFT,   MASK_SFPSHFT,   sfp_match_opcode, INSN_ALIAS },
{"sfpabs",     0, INSN_CLASS_I_Y,   "Jh,Jg,Ji2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpabs",     0, INSN_CLASS_I_W,   "wh,wg,wi2",      MATCH_SFPABS,    MASK_SFPABS,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_I_Y,   "Jh,Jg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpand",     0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPAND,    MASK_SFPAND,    sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_I_Y,   "Jh,Jg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpor",      0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPOR,     MASK_SFPOR,     sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_I_Y,   "Jh,Jg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfpnot",     0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPNOT,    MASK_SFPNOT,    sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_I_Y,   "Jh,Jg,Ji6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfplz",      0, INSN_CLASS_I_W,   "wh,wg,wi6",      MATCH_SFPLZ,     MASK_SFPLZ,     sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetexp",  0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSETEXP, MASK_SFPSETEXP, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetman",  0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSETMAN, MASK_SFPSETMAN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_I_Y,   "Jh,Jg,Jf,Ji2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpsetsgn",  0, INSN_CLASS_I_W,   "wh,wg,wf,wi2",   MATCH_SFPSETSGN, MASK_SFPSETSGN, sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_I_Y,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmad",     0, INSN_CLASS_I_W,   "we,wa,wb,wc,wo", MATCH_SFPMAD,    MASK_SFPMAD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_I_Y,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpadd",     0, INSN_CLASS_I_W,   "we,wa,wb,wc,wo", MATCH_SFPADD,    MASK_SFPADD,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_I_Y,   "Je,Ja,Jb,Jc,Jo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpmul",     0, INSN_CLASS_I_W,   "we,wa,wb,wc,wo", MATCH_SFPMUL,    MASK_SFPMUL,    sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_I_Y,   "Jf,Ji6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpencc",    0, INSN_CLASS_I_W,   "wf,wi6",         MATCH_SFPENCC,   MASK_SFPENCC,   sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_I_Y,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },
{"sfpcompc",   0, INSN_CLASS_I_W,   "",               MATCH_SFPCOMPC,  MASK_SFPCOMPC,  sfp_match_opcode, INSN_ALIAS },
{"sfppushc",   0, INSN_CLASS_I_Y,   "",               MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },
{"sfppushc",   0, INSN_CLASS_I_W,   "wi1",            MATCH_SFPPUSHC,  MASK_SFPPUSHC,  sfp_match_opcode, INSN_ALIAS },
{"sfppopc",    0, INSN_CLASS_I_Y,   "",               MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfppopc",    0, INSN_CLASS_I_W,   "wi1",            MATCH_SFPPOPC,   MASK_SFPPOPC,   sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_I_Y,   "Jg,Jf,Ji1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpsetcc",   0, INSN_CLASS_I_W,   "wg,wf,wi1",      MATCH_SFPSETCC,  MASK_SFPSETCC,  sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_I_Y,   "Jh,Jg,Ji2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"sfpmov",     0, INSN_CLASS_I_W,   "wh,wg,wi2",      MATCH_SFPMOV,    MASK_SFPMOV,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_I_Y,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"ttnop",      0, INSN_CLASS_I_W,   "",               MATCH_SFPNOP,    MASK_SFPNOP,    sfp_match_opcode, INSN_ALIAS },
{"sfpnop",     0, INSN_CLASS_I_W,   "",               MATCH_SFPWNOP,   MASK_SFPWNOP,   sfp_match_opcode, 0 },
{"ttincrwc",   0, INSN_CLASS_I_Y,   "Jk1,Jk2,Jk3,Jk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttincrwc",   0, INSN_CLASS_I_W,   "wk1,wk2,wk3,wk4",MATCH_SFPINCRWC, MASK_SFPINCRWC, sfp_match_opcode, INSN_ALIAS },
{"ttreplay",   0, INSN_CLASS_I_W,   "wl1,wl2,wl3,wl4",MATCH_SFPREPLAY, MASK_SFPREPLAY, sfp_match_opcode, 0 },
{"sfpxor",     0, INSN_CLASS_I_W,   "wh,wg",          MATCH_SFPXOR,    MASK_SFPXOR,    sfp_match_opcode, 0 },
{"sfpcast",    0, INSN_CLASS_I_W,   "we,wc,wi2",      MATCH_SFPCAST,   MASK_SFPCAST,   sfp_match_opcode, 0 },
{"sfpshft2",   0, INSN_CLASS_I_W,   "we,wc,wi2",      MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, 0 },
{"sfpshft2",   0, INSN_CLASS_I_W,   "we,wc,wf,wi2",   MATCH_SFPSHFT2,  MASK_SFPSHFT2,  sfp_match_opcode, INSN_ALIAS },
{"sfpconfig",  0, INSN_CLASS_I_W,   "wh,wj,wi7",      MATCH_SFPCONFIG, MASK_SFPCONFIG, sfp_match_opcode, 0 },
{"sfpswap",    0, INSN_CLASS_I_W,   "wh,wg,wi8",      MATCH_SFPSWAP,   MASK_SFPSWAP,   sfp_match_opcode, 0 },
{"sfplutfp32", 0, INSN_CLASS_I_W,   "we,wo",          MATCH_SFPLUTFP32,MASK_SFPLUTFP32,sfp_match_opcode, 0 },
{"sfptransp",  0, INSN_CLASS_I_W,   "",               MATCH_SFPTRANSP, MASK_SFPTRANSP, sfp_match_opcode, 0 },
{"sfploadmacro",0, INSN_CLASS_I_W,  "wd,wq,wm1,wp",   MATCH_SFPLDMACRO,MASK_SFPLDMACRO,sfp_match_opcode, 0 },
{"sfpstochrnd",0, INSN_CLASS_I_W,   "we,wb,wc,wi1,wr1,wr2", MATCH_SFPSTOCH_RND,    MASK_SFPSTOCH_RND,    sfp_match_opcode, 0 },
