/* SFPU Instructions */
#define SFP_OPCODE_START 0x70
#define MATCH_SFPLOAD 0x70000003
#define MASK_SFPLOAD  0xffffffff
#define MATCH_SFPLOADI 0x71000003
#define MASK_SFPLOADI  0xffffffff
#define MATCH_SFPSTORE 0x72000003
#define MASK_SFPSTORE  0xffffffff

#define MATCH_SFPMAD 0x84000003
#define MASK_SFPMAD  0xffffffff

#define MATCH_SFPENCC 0x8a000003
#define MASK_SFPENCC  0xffffffff
#define MATCH_SFPCOMPC 0x8b000003
#define MASK_SFPCOMPC  0xffffffff
#define MATCH_SFPPUSHC 0x87000003
#define MASK_SFPPUSHC  0xffffffff
#define MATCH_SFPPOPC 0x88000003
#define MASK_SFPPOPC  0xffffffff
#define MATCH_SFPSETCC 0x7b000003
#define MASK_SFPSETCC  0xffffffff
#define MATCH_SFPMOV 0x7c000003
#define MASK_SFPMOV  0xffffffff

#define MATCH_SFPLUT   0x73000003
#define MASK_SFPLUT    0xffffffff
#define MATCH_SFPMULI   0x74000003
#define MASK_SFPMULI    0xffffffff
#define MATCH_SFPADDI   0x75000003
#define MASK_SFPADDI    0xffffffff
#define MATCH_SFPDIVP2   0x76000003
#define MASK_SFPDIVP2    0xffffffff
#define MATCH_SFPEXEXP   0x77000003
#define MASK_SFPEXEXP    0xffffffff
#define MATCH_SFPEXMAN   0x78000003
#define MASK_SFPEXMAN    0xffffffff
#define MATCH_SFPIADD   0x79000003
#define MASK_SFPIADD    0xffffffff
#define MATCH_SFPSHFT   0x7a000003
#define MASK_SFPSHFT    0xffffffff
#define MATCH_SFPABS   0x7d000003
#define MASK_SFPABS    0xffffffff
#define MATCH_SFPAND   0x7e000003
#define MASK_SFPAND    0xffffffff
#define MATCH_SFPOR   0x7f000003
#define MASK_SFPOR    0xffffffff
#define MATCH_SFPNOT   0x80000003
#define MASK_SFPNOT    0xffffffff
#define MATCH_SFPLZ   0x81000003
#define MASK_SFPLZ    0xffffffff
#define MATCH_SFPSETEXP   0x82000003
#define MASK_SFPSETEXP    0xffffffff
#define MATCH_SFPSETMAN   0x83000003
#define MASK_SFPSETMAN    0xffffffff
#define MATCH_SFPADD   0x85000003
#define MASK_SFPADD    0xffffffff
#define MATCH_SFPMUL   0x86000003
#define MASK_SFPMUL    0xffffffff
#define MATCH_SFPSETSGN   0x89000003
#define MASK_SFPSETSGN    0xffffffff

#define MATCH_SFPNOP   0x02000003
#define MASK_SFPNOP    0xffffffff

#define MATCH_SFPINCRWC 0x38000003
#define MASK_SFPINCRWC 0xffffffff
#define MATCH_SFPREPLAY 0x04000003
#define MASK_SFPREPLAY 0xffffffff

#define MATCH_SFPTRANSP 0x8c000003
#define MASK_SFPTRANSP 0xffffffff
#define MATCH_SFPXOR 0x8d000003
#define MASK_SFPXOR 0xffffffff
#define MATCH_SFPSTOCH_RND 0x8e000003
#define MASK_SFPSTOCH_RND 0xffffffff
#define MATCH_SFPWNOP 0x8f000003
#define MASK_SFPWNOP 0xffffffff
#define MATCH_SFPCAST 0x90000003
#define MASK_SFPCAST 0xffffffff
#define MATCH_SFPCONFIG 0x91000003
#define MASK_SFPCONFIG 0xffffffff
#define MATCH_SFPSWAP 0x92000003
#define MASK_SFPSWAP 0xffffffff
#define MATCH_SFPLDMACRO 0x93000003
#define MASK_SFPLDMACRO 0xffffffff
#define MATCH_SFPSHFT2 0x94000003
#define MASK_SFPSHFT2 0xffffffff
#define MATCH_SFPLUTFP32 0x95000003
#define MASK_SFPLUTFP32 0xffffffff

#ifdef DECLARE_INSN
/* SFPU Instructions */
DECLARE_INSN(SFPLOAD, MATCH_SFPLOAD, MASK_SFPLOAD)
DECLARE_INSN(SFPLOADI, MATCH_SFPLOADI, MASK_SFPLOADI)
DECLARE_INSN(SFPSTORE, MATCH_SFPSTORE, MASK_SFPSTORE)

DECLARE_INSN(SFPMAD, MATCH_SFPMAD, MASK_SFPMAD)

DECLARE_INSN(SFPENCC, MATCH_SFPENCC, MASK_SFPENCC)
DECLARE_INSN(SFPCOMPC, MATCH_SFPCOMPC, MASK_SFPCOMPC)
DECLARE_INSN(SFPPUSHC, MATCH_SFPPUSHC, MASK_SFPPUSHC)
DECLARE_INSN(SFPPOPC, MATCH_SFPPOPC, MASK_SFPPOPC)
DECLARE_INSN(SFPSETCC, MATCH_SFPSETCC, MASK_SFPSETCC)
DECLARE_INSN(SFPMOV, MATCH_SFPMOV, MASK_SFPMOV)

DECLARE_INSN(SFPLUT, MATCH_SFPLUT, MASK_SFPLUT)
DECLARE_INSN(SFPMULI, MATCH_SFPMULI, MASK_SFPMULI)
DECLARE_INSN(SFPADDI, MATCH_SFPADDI, MASK_SFPADDI)
DECLARE_INSN(SFPDIVP2, MATCH_SFPDIVP2, MASK_SFPDIVP2)
DECLARE_INSN(SFPEXEXP, MATCH_SFPEXEXP, MASK_SFPEXEXP)
DECLARE_INSN(SFPEXMAN, MATCH_SFPEXMAN, MASK_SFPEXMAN)
DECLARE_INSN(SFPIADD, MATCH_SFPIADD, MASK_SFPIADD)
DECLARE_INSN(SFPSHFT, MATCH_SFPSHFT, MASK_SFPSHFT)
DECLARE_INSN(SFPABS, MATCH_SFPABS, MASK_SFPABS)
DECLARE_INSN(SFPAND, MATCH_SFPAND, MASK_SFPAND)
DECLARE_INSN(SFPOR, MATCH_SFPOR, MASK_SFPOR)
DECLARE_INSN(SFPNOT, MATCH_SFPNOT, MASK_SFPNOT)
DECLARE_INSN(SFPLZ, MATCH_SFPLZ, MASK_SFPLZ)
DECLARE_INSN(SFPSETEXP, MATCH_SFPSETEXP, MASK_SFPSETEXP)
DECLARE_INSN(SFPSETMAN, MATCH_SFPSETMAN, MASK_SFPSETMAN)
DECLARE_INSN(SFPADD, MATCH_SFPADD, MASK_SFPADD)
DECLARE_INSN(SFPMUL, MATCH_SFPMUL, MASK_SFPMUL)
DECLARE_INSN(SFPSETSGN, MATCH_SFPSETSGN, MASK_SFPSETSGN)

DECLARE_INSN(SFPNOP, MATCH_SFPNOP, MASK_SFPNOP)
#endif
