.*: Assembler messages:
.*:2: Error: immediate operand .49. not in range .0,48.
.*:2: Error: illegal operands .tt.rocc.scmdbuf_wr_reg x0,49,a1,x0.
.*:3: Error: immediate operand .-1. not in range .0,48.
.*:3: Error: illegal operands .tt.rocc.scmdbuf_wr_reg x0,-1,a1,x0.
.*:5: Error: immediate operand .49. not in range .0,48.
.*:5: Error: illegal operands .tt.rocc.scmdbuf_rd_reg a0,49,x0,x0.
.*:6: Error: immediate operand .-1. not in range .0,48.
.*:6: Error: illegal operands .tt.rocc.scmdbuf_rd_reg a0,-1,x0,x0.
